// arm64.go — Plan 9 ARM64 code generator for gaston.
//
// Calling convention: AAPCS64 (Linux ARM64 ABI)
//   Arguments:    R0–R7 (first 8 integers or pointers)
//   Return value: R0
//   Callee-saves: R19–R28, R29 (FP), R30 (LR)
//   Caller-saved: R0–R17 (we only use R0–R2 as scratch)
//   SP must be 16-byte aligned at every BL instruction.
//
// Stack frame layout (AAPCS64 frame record at bottom):
//   RSP+0          saved R29 (FP) — frame record low word
//   RSP+8          saved R30 (LR) — frame record high word
//   R29 = RSP      (frame pointer points at frame record)
//   RSP+16 ..      params (8 bytes each, even array params which are pointers)
//   RSP+16+8*np .. local scalars (8 bytes each)
//                  local arrays (size*8 bytes each, contiguous)
//   ...            temporaries (8 bytes each)
//   Frame padded to 16-byte alignment.
//
// Generated symbol names: gaston_<funcname> for functions,
//                         gaston_<varname> for globals.
// Built-in I/O: gaston_input() and gaston_output(int64) must be provided
//               by the linking Go package (see runtime interface comment below).
package main

import (
	"fmt"
	"io"
	"math"
	"strings"
)

// frame holds the computed stack layout for one function.
type frame struct {
	offsets   map[string]int  // name → byte offset from RSP (or RFP when hasVLA)
	isArrPtr  map[string]bool // true if the name is an array-param (pointer slot)
	isArrBase map[string]bool // true if the name is a local array (inline storage)
	isPtrVar  map[string]bool // true if the name is a pointer variable (int* or char*)
	hasVLA    bool            // true if function contains any VLA — use FP-relative addressing
	frameSize int
}

// paramArg is one pending call argument (accumulated between IRParam/IRFParam and IRCall).
type paramArg struct {
	addr      IRAddr
	isFP      bool   // true → FP argument (goes to F0–F7); false → integer (goes to R0–R7)
	isStruct  bool   // true → struct-by-value argument
	structTag string // non-empty when isStruct: struct type name for size dispatch
}

// arm64Gen emits Plan 9 ARM64 assembly for an IRProgram.
type arm64Gen struct {
	w             io.Writer
	pendingParams []paramArg // params accumulate before each IRCall
	localLabelN   int        // counter for synthetic comparison labels
	structDefs    map[string]*StructDef // struct type definitions (for struct-return size dispatch)
}

// genARM64 is the entry point: writes a complete .s file to w.
func genARM64(irp *IRProgram, w io.Writer) {
	g := &arm64Gen{w: w, structDefs: irp.StructDefs}

	g.line("// Code generated by gaston — C-minus → ARM64 Plan 9 assembler")
	g.line("// DO NOT EDIT")
	g.line("//")
	g.line("// Runtime interface (provide these in Go):")
	g.line("//   func gaston_input() int64            // reads one integer from stdin")
	g.line("//   func gaston_output(v int64)           // writes one integer to stdout")
	g.line("//   func gaston_main()                    // call to run the program")
	g.line("#include \"textflag.h\"")
	g.line("")

	// Global variable declarations.
	for _, gbl := range irp.Globals {
		bytes := gbl.Size * 8
		g.linef("GLOBL gaston_%s(SB), NOPTR, $%d", gbl.Name, bytes)
	}
	if len(irp.Globals) > 0 {
		g.line("")
	}

	// String literal rodata (Plan 9: DATA + GLOBL).
	for _, sl := range irp.StrLits {
		content := sl.Content + "\x00" // NUL-terminate
		g.linef("GLOBL gaston_%s(SB), RODATA, $%d", sl.Label, len(content))
		for i := 0; i < len(content); i++ {
			g.linef("DATA gaston_%s+%d(SB)/1, $0x%02X", sl.Label, i, content[i])
		}
	}
	if len(irp.StrLits) > 0 {
		g.line("")
	}

	// FP constant literal pool (Plan 9: DATA + GLOBL, 8 bytes each).
	for _, fc := range irp.FConsts {
		bits := math.Float64bits(fc.Value)
		g.linef("GLOBL gaston_%s(SB), RODATA, $8", fc.Label)
		g.linef("DATA gaston_%s+0(SB)/8, $0x%016X", fc.Label, bits)
	}
	if len(irp.FConsts) > 0 {
		g.line("")
	}

	// Functions.
	for _, fn := range irp.Funcs {
		g.genFunc(fn, irp.StructDefs)
	}
}

// ── helpers ──────────────────────────────────────────────────────────────────

func (g *arm64Gen) line(s string)                        { fmt.Fprintln(g.w, s) }
func (g *arm64Gen) linef(f string, a ...interface{})     { fmt.Fprintf(g.w, f+"\n", a...) }
func (g *arm64Gen) insn(s string)                        { fmt.Fprintln(g.w, "\t"+s) }
func (g *arm64Gen) insnf(f string, a ...interface{})     { fmt.Fprintf(g.w, "\t"+f+"\n", a...) }

func (g *arm64Gen) newCmpLabel(fn *IRFunc) string {
	l := fmt.Sprintf("gaston_%s_cmp%d", fn.Name, g.localLabelN)
	g.localLabelN++
	return l
}

// ── frame layout ─────────────────────────────────────────────────────────────

func buildFrame(fn *IRFunc, structDefs map[string]*StructDef) *frame {
	f := &frame{
		offsets:   make(map[string]int),
		isArrPtr:  make(map[string]bool),
		isArrBase: make(map[string]bool),
		isPtrVar:  make(map[string]bool),
		hasVLA:    fn.HasVLA,
	}
	offset := 16 // RSP+0 = LR, RSP+8 = FP, locals start at 16.

	// Parameters: scalar/array/pointer params get 8-byte slots; struct params
	// skip this section entirely — their storage comes from fn.Locals below.
	for i, name := range fn.Params {
		if i < len(fn.ParamType) && fn.ParamType[i] == TypeStruct {
			continue // full storage is in fn.Locals (isArrBase); no scalar slot here
		}
		f.offsets[name] = offset
		if i < len(fn.ParamType) {
			switch fn.ParamType[i] {
			case TypeIntArray:
				f.isArrPtr[name] = true
			case TypePtr, TypeCharPtr:
				f.isPtrVar[name] = true
			}
		}
		offset += 8
	}

	// Variadic register save area: always reserve RSP+24..RSP+72 for X1..X7.
	if fn.IsVariadic {
		minOffset := 16 + 8*8 // = 80: enough space for X0..X7
		if offset < minOffset {
			offset = minOffset
		}
	}

	// Local variables (declared in function body).
	for _, loc := range fn.Locals {
		f.offsets[loc.Name] = offset
		if loc.IsVLA {
			// VLA: the frame slot holds the runtime base pointer (8 bytes).
			// The actual array lives below FP on the stack after IRVLAAlloc.
			f.isArrPtr[loc.Name] = true
			offset += 8
		} else if loc.IsArray {
			f.isArrBase[loc.Name] = true
			offset += loc.ArrSize * 8
		} else if loc.IsStruct {
			// Struct locals: inline storage, treated like an array base.
			// Round up to 8-byte boundary so subsequent frame slots are 8-byte
			// aligned (required by encLDRuoff/encSTRuoff which scale by 8).
			f.isArrBase[loc.Name] = true
			if sd, ok := structDefs[loc.StructTag]; ok {
				sz := sd.SizeBytes(structDefs)
				offset += (sz + 7) &^ 7
			} else {
				offset += loc.ArrSize * 8 // fallback
			}
		} else {
			if loc.IsPtr {
				f.isPtrVar[loc.Name] = true
			}
			offset += 8
		}
	}

	// Temporaries: scan all quads.
	for _, q := range fn.Quads {
		for _, addr := range [3]IRAddr{q.Dst, q.Src1, q.Src2} {
			if addr.Kind == AddrTemp {
				if _, seen := f.offsets[addr.Name]; !seen {
					f.offsets[addr.Name] = offset
					offset += 8
				}
			}
		}
	}

	// 16-byte alignment.
	if offset%16 != 0 {
		offset += 16 - (offset % 16)
	}
	f.frameSize = offset
	return f
}

// ── function emission ─────────────────────────────────────────────────────────

func (g *arm64Gen) genFunc(fn *IRFunc, structDefs map[string]*StructDef) {
	f := buildFrame(fn, structDefs)
	g.localLabelN = 0

	g.linef("// func %s(%s)", fn.Name, paramSig(fn))
	g.linef("TEXT gaston_%s(SB), NOSPLIT, $0", fn.Name)

	// Prologue (AAPCS64): allocate frame, establish frame record, copy args.
	g.insnf("SUB $%d, RSP, RSP", f.frameSize)
	g.insn("MOVD R29, 0(RSP)")   // save FP  (frame record low word)
	g.insn("MOVD R30, 8(RSP)")   // save LR  (frame record high word)
	g.insn("MOVD RSP, R29")      // FP = SP  (frame pointer chain)
	iIdx := 0
	for i, name := range fn.Params {
		if iIdx >= 8 {
			break
		}
		pt := TypeInt
		if i < len(fn.ParamType) {
			pt = fn.ParamType[i]
		}
		if pt == TypeStruct {
			off := f.offsets[name]
			tag := ""
			if i < len(fn.ParamStructTag) {
				tag = fn.ParamStructTag[i]
			}
			var size int
			if sd, ok := g.structDefs[tag]; ok {
				size = sd.SizeBytes(g.structDefs)
			}
			switch {
			case size <= 8:
				g.insnf("MOVD R%d, %d(RSP)", iIdx, off)
				iIdx++
			case size <= 16:
				g.insnf("MOVD R%d, %d(RSP)", iIdx, off)
				g.insnf("MOVD R%d, %d(RSP)", iIdx+1, off+8)
				iIdx += 2
			default:
				numWords := (size + 7) / 8
				g.insnf("MOVD R%d, R9", iIdx) // R9 = caller's pointer
				for w := 0; w < numWords; w++ {
					g.insnf("MOVD %d(R9), R10", w*8)
					g.insnf("MOVD R10, %d(RSP)", off+w*8)
				}
				iIdx++
			}
		} else {
			g.insnf("MOVD R%d, %d(RSP)", iIdx, f.offsets[name])
			iIdx++
		}
	}
	// Variadic: save X1..X7 to frame slots RSP+24..RSP+72.
	if fn.IsVariadic {
		for i := 1; i <= 7; i++ {
			g.insnf("MOVD R%d, %d(RSP)", i, 16+8*i)
		}
	}
	// Struct return (>16 bytes): X8 holds the caller's destination pointer on entry.
	// Save it before any inner call can clobber it.
	if fn.ReturnStructTag != "" {
		if sd, ok := g.structDefs[fn.ReturnStructTag]; ok && sd.SizeBytes(g.structDefs) > 16 {
			if off, ok2 := f.offsets["__x8_save"]; ok2 {
				g.insnf("MOVD R8, %d(RSP)", off)
			}
		}
	}
	g.line("")

	// Instruction stream.
	for qi, q := range fn.Quads {
		_ = qi
		switch q.Op {
		case IREnter:
			// Prologue already emitted above.

		case IRLabel:
			g.linef("gaston_%s_%s:", fn.Name, q.Extra)

		case IRJump:
			g.insnf("B gaston_%s_%s", fn.Name, q.Extra)

		case IRJumpT:
			g.emit_load(f, q.Src1, "R0")
			g.insn("CMP $0, R0")
			g.insnf("BNE gaston_%s_%s", fn.Name, q.Extra)

		case IRJumpF:
			g.emit_load(f, q.Src1, "R0")
			g.insn("CMP $0, R0")
			g.insnf("BEQ gaston_%s_%s", fn.Name, q.Extra)

		case IRCopy:
			g.emit_load(f, q.Src1, "R0")
			g.emit_store(f, "R0", q.Dst)

		case IRAdd:
			g.emitArith(f, q, "ADD")
		case IRSub:
			g.emitArith(f, q, "SUB")
		case IRMul:
			g.emitArith(f, q, "MUL")
		case IRDiv:
			g.emitArith(f, q, "SDIV")
		case IRMod:
			g.emitMod(f, q)
		case IRUDiv:
			g.emitArith(f, q, "UDIV")
		case IRUMod:
			g.emitUMod(f, q)
		case IRBitAnd:
			g.emitArith(f, q, "AND")
		case IRBitOr:
			g.emitArith(f, q, "ORR")
		case IRBitXor:
			g.emitArith(f, q, "EOR")
		case IRShl:
			g.emitArith(f, q, "LSL")
		case IRShr:
			g.emitArith(f, q, "ASR")
		case IRUShr:
			g.emitArith(f, q, "LSR")
		case IRBitNot:
			g.emit_load(f, q.Src1, "R0")
			g.insn("MVN R0, R0")
			g.emit_store(f, "R0", q.Dst)

		case IRLt:
			g.emitCmpBool(f, fn, q, "BLT")
		case IRLe:
			g.emitCmpBool(f, fn, q, "BLE")
		case IRGt:
			g.emitCmpBool(f, fn, q, "BGT")
		case IRGe:
			g.emitCmpBool(f, fn, q, "BGE")
		case IREq:
			g.emitCmpBool(f, fn, q, "BEQ")
		case IRNe:
			g.emitCmpBool(f, fn, q, "BNE")
		case IRULt:
			g.emitCmpBool(f, fn, q, "BLO")
		case IRULe:
			g.emitCmpBool(f, fn, q, "BLS")
		case IRUGt:
			g.emitCmpBool(f, fn, q, "BHI")
		case IRUGe:
			g.emitCmpBool(f, fn, q, "BHS")

		case IRLoad:
			g.emitArrayLoad(f, q)
		case IRStore:
			g.emitArrayStore(f, q)
		case IRCharLoad:
			g.emitCharArrayLoad(f, q)
		case IRCharStore:
			g.emitCharArrayStore(f, q)
		case IRGetAddr:
			g.emitAddrOf(f, q)
		case IRAddrOf:
			g.emitAddrOf(f, q)

		case IRSignExtend:
			// Dst = sign_extend(Src1, bits) — integer promotion for char/short.
			g.emit_load(f, q.Src1, "R0")
			if q.Src2.IVal == 8 {
				g.insn("SXTB R0, R0")
			} else {
				g.insn("SXTH R0, R0")
			}
			g.emit_store(f, "R0", q.Dst)

		case IRZeroExtend:
			// Dst = zero_extend(Src1, bits) — integer promotion for unsigned char/short.
			g.emit_load(f, q.Src1, "R0")
			if q.Src2.IVal == 8 {
				g.insn("UXTB R0, R0")
			} else {
				g.insn("UXTH R0, R0")
			}
			g.emit_store(f, "R0", q.Dst)

		case IRStrAddr:
			// Plan 9 path: load address of a rodata symbol.
			g.insnf("MOVD $gaston_%s(SB), R0", q.Extra)
			g.emit_store(f, "R0", q.Dst)

		case IRDerefLoad:
			// R0 = *Src1 (load via pointer)
			g.emit_load(f, q.Src1, "R0")
			g.insn("MOVD (R0), R0")
			g.emit_store(f, "R0", q.Dst)

		case IRDerefStore:
			// *Dst = Src1
			g.emit_load(f, q.Dst, "R0")  // R0 = pointer
			g.emit_load(f, q.Src1, "R1") // R1 = value
			g.insn("MOVD R1, (R0)")

		case IRFDerefLoad:
			// Dst = *Src1 (load 8-byte double via pointer; result is FP)
			g.emit_load(f, q.Src1, "R0")      // R0 = pointer
			g.insn("FMOVD (R0), F0")           // F0 = *R0
			g.emit_fp_store(f, "F0", q.Dst)

		case IRFDerefStore:
			// *Dst = Src1 (store 8-byte double via pointer; Src1 is FP)
			g.emit_load(f, q.Dst, "R0")        // R0 = pointer
			g.emit_fp_load(f, q.Src1, "F0")    // F0 = Src1
			g.insn("FMOVD F0, (R0)")            // *R0 = F0

		case IRDerefCharLoad:
			// Dst = *(byte*)Src1 — zero-extended 1-byte load via computed pointer
			g.emit_load(f, q.Src1, "R0") // R0 = byte address
			g.insn("MOVBU (R0), R0")     // R0 = zero-extended byte
			g.emit_store(f, "R0", q.Dst)

		case IRDerefCharStore:
			// *(byte*)Dst = Src1 — 1-byte store via computed pointer
			g.emit_load(f, q.Dst, "R0")  // R0 = byte address
			g.emit_load(f, q.Src1, "R1") // R1 = value
			g.insn("MOVB R1, (R0)")      // store byte

		// ── floating-point operations ────────────────────────────────────
		case IRFAdd:
			g.emitFPArith(f, q, "FADDD")
		case IRFSub:
			g.emitFPArith(f, q, "FSUBD")
		case IRFMul:
			g.emitFPArith(f, q, "FMULD")
		case IRFDiv:
			g.emitFPArith(f, q, "FDIVD")

		case IRFNeg:
			g.emit_fp_load(f, q.Src1, "F0")
			g.insn("FNEGD F0, F0")
			g.emit_fp_store(f, "F0", q.Dst)

		case IRFCopy:
			g.emit_fp_load(f, q.Src1, "F0")
			g.emit_fp_store(f, "F0", q.Dst)

		case IRFLt:
			g.emitFPCmpBool(f, fn, q, "BLT")
		case IRFLe:
			g.emitFPCmpBool(f, fn, q, "BLE")
		case IRFGt:
			g.emitFPCmpBool(f, fn, q, "BGT")
		case IRFGe:
			g.emitFPCmpBool(f, fn, q, "BGE")
		case IRFEq:
			g.emitFPCmpBool(f, fn, q, "BEQ")
		case IRFNe:
			g.emitFPCmpBool(f, fn, q, "BNE")

		case IRIntToDouble:
			g.emit_load(f, q.Src1, "R0")
			g.insn("SCVTFD R0, F0")
			g.emit_fp_store(f, "F0", q.Dst)

		case IRDoubleToInt:
			g.emit_fp_load(f, q.Src1, "F0")
			g.insn("FCVTZSD F0, R0")
			g.emit_store(f, "R0", q.Dst)

		case IRFBitcastFI:
			g.emit_fp_load(f, q.Src1, "F0")
			g.insn("FMOVD F0, R0") // FMOV R0, F0 — copy bits, no conversion
			g.emit_store(f, "R0", q.Dst)
		case IRFBitcastIF:
			g.emit_load(f, q.Src1, "R0")
			g.insn("FMOVD R0, F0") // FMOV F0, R0 — copy bits, no conversion
			g.emit_fp_store(f, "F0", q.Dst)

		case IRStructCopy:
			// x = y: copy all 8-byte words from Src1 (src addr) to Dst (dst addr).
			sd := g.structDefs[q.StructTag]
			if sd != nil {
				size := sd.SizeBytes(g.structDefs)
				numWords := (size + 7) / 8
				g.structBase(f, q.Src1, "R9") // R9 = src base
				g.structBase(f, q.Dst, "R10") // R10 = dst base
				for i := 0; i < numWords; i++ {
					g.insnf("MOVD %d(R9), R11", i*8)
					g.insnf("MOVD R11, %d(R10)", i*8)
				}
			}

		case IRParam:
			if q.TypeHint == TypeStruct {
				g.pendingParams = append(g.pendingParams, paramArg{
					addr: q.Src1, isStruct: true, structTag: q.StructTag,
				})
			} else {
				g.pendingParams = append(g.pendingParams, paramArg{addr: q.Src1, isFP: false})
			}

		case IRFParam:
			g.pendingParams = append(g.pendingParams, paramArg{addr: q.Src1, isFP: true})

		case IRCall:
			g.emitCall(f, fn, q)

		case IRFieldLoad:
			// Dst = *(Src1 + Src2.IVal) — field load; width from TypeHint
			g.emit_load(f, q.Src1, "R0")
			g.emit_load(f, q.Src2, "R1")
			g.insn("ADD R1, R0, R0")
			switch q.TypeHint {
			case TypeChar:
				g.insn("MOVB (R0), R0")  // sign-extend byte
			case TypeUnsignedChar:
				g.insn("MOVBU (R0), R0") // zero-extend byte
			case TypeShort:
				g.insn("MOVH (R0), R0")  // sign-extend halfword
			case TypeUnsignedShort:
				g.insn("MOVHU (R0), R0") // zero-extend halfword
			case TypeInt:
				g.insn("MOVW (R0), R0")  // LDRSW: sign-extend 32-bit word
			case TypeUnsignedInt:
				g.insn("MOVWU (R0), R0") // LDR W: zero-extend 32-bit word
			default:
				g.insn("MOVD (R0), R0")  // 8-byte load
			}
			g.emit_store(f, "R0", q.Dst)

		case IRFFieldLoad:
			// Dst = *(Src1 + Src2.IVal) — load FP field at byte offset; width from TypeHint
			g.emit_load(f, q.Src1, "R0")
			g.emit_load(f, q.Src2, "R1")
			g.insn("ADD R1, R0, R0")
			if q.TypeHint == TypeFloat {
				g.insn("FMOVS (R0), F0")  // LDR S0: load 32-bit float
				g.insn("FCVTSD F0, F0")   // FCVT D0, S0: single → double
			} else {
				g.insn("FMOVD (R0), F0")  // LDR D0: load 64-bit double
			}
			g.emit_fp_store(f, "F0", q.Dst)

		case IRFieldStore:
			// *(Dst + Src2.IVal) = Src1 — field store; width from TypeHint
			g.emit_load(f, q.Dst, "R0")
			g.emit_load(f, q.Src2, "R1")
			g.insn("ADD R1, R0, R0")
			g.emit_load(f, q.Src1, "R2")
			switch q.TypeHint {
			case TypeChar, TypeUnsignedChar:
				g.insn("MOVB R2, (R0)")  // store 1 byte
			case TypeShort, TypeUnsignedShort:
				g.insn("MOVH R2, (R0)")  // store 2 bytes
			case TypeInt, TypeUnsignedInt:
				g.insn("MOVW R2, (R0)")  // STR W: store 4 bytes
			default:
				g.insn("MOVD R2, (R0)")  // store 8 bytes
			}

		case IRFFieldStore:
			// *(Dst + Src2.IVal) = Src1 — store FP to field at byte offset; width from TypeHint
			g.emit_load(f, q.Dst, "R0")
			g.emit_load(f, q.Src2, "R1")
			g.insn("ADD R1, R0, R0")
			g.emit_fp_load(f, q.Src1, "F0")
			if q.TypeHint == TypeFloat {
				g.insn("FCVTDS F0, F0")   // FCVT S0, D0: double → single
				g.insn("FMOVS F0, (R0)")  // STR S0: store 32-bit float
			} else {
				g.insn("FMOVD F0, (R0)")  // STR D0: store 64-bit double
			}

		case IRVLAAlloc:
			// Allocate Src1*8 bytes on the stack (16-byte aligned), store base in Dst.
			// Plan 9 assembly: R0 = size, compute aligned bytes, SUB from RSP.
			g.emit_load(f, q.Src1, "R0")
			g.insn("LSL $3, R0, R0")          // R0 = n * 8
			g.insn("ADD $15, R0, R0")          // R0 += 15 (round-up bias)
			g.insn("AND $-16, R0, R0")         // R0 &= ~15 (align to 16)
			g.insn("SUB R0, RSP, RSP")         // SP -= aligned_size
			g.insn("MOVD RSP, R0")             // R0 = new SP (VLA base)
			g.emit_store(f, "R0", q.Dst)       // store VLA base pointer in frame slot

		case IRFuncAddr:
			// Load the virtual address of a named function into a temporary.
			// Plan 9 ARM64: MOVD $gaston_name(SB), R0
			g.insnf("MOVD $gaston_%s(SB), R0", q.Extra)
			g.emit_store(f, "R0", q.Dst)

		case IRFuncPtrCall:
			// Call through a function pointer.
			// First flush pending args into R0–R7 / F0–F7, then load the
			// function pointer into R16 (scratch register), then CALL (R16).
			iIdx, fIdx := 0, 0
			for _, p := range g.pendingParams {
				if p.isFP {
					if fIdx < 8 {
						g.emit_fp_load(f, p.addr, fmt.Sprintf("F%d", fIdx))
						fIdx++
					}
				} else {
					if iIdx < 8 {
						g.emit_load(f, p.addr, fmt.Sprintf("R%d", iIdx))
						iIdx++
					}
				}
			}
			g.pendingParams = g.pendingParams[:0]
			g.emit_load(f, q.Src1, "R16")
			g.insn("CALL (R16)")
			if q.Dst.Kind != AddrNone {
				g.emit_store(f, "R0", q.Dst)
			}

		case IRReturn:
			if q.TypeHint == TypeStruct && q.StructTag != "" {
				g.emitStructReturn(f, q)
			} else {
				if q.Src1.Kind != AddrNone {
					g.emit_load(f, q.Src1, "R0")
				}
				g.emitEpilogue(f)
			}
		}
	}

	g.line("")
}

// ── load / store helpers ──────────────────────────────────────────────────────

// emit_load loads addr into reg.
func (g *arm64Gen) emit_load(f *frame, addr IRAddr, reg string) {
	switch addr.Kind {
	case AddrConst:
		g.insnf("MOVD $%d, %s", addr.IVal, reg)
	case AddrTemp, AddrLocal:
		off, ok := f.offsets[addr.Name]
		if !ok {
			g.insnf("// BUG: no offset for %s", addr.Name)
			return
		}
		g.insnf("MOVD %d(RSP), %s", off, reg)
	case AddrGlobal:
		g.insnf("MOVD gaston_%s(SB), %s", addr.Name, reg)
	case AddrFConst:
		g.insnf("FMOVD gaston_%s(SB), %s", addr.Name, reg)
	default:
		g.insn("// emit_load: AddrNone")
	}
}

// emit_store stores reg into dst.
func (g *arm64Gen) emit_store(f *frame, reg string, dst IRAddr) {
	switch dst.Kind {
	case AddrTemp, AddrLocal:
		off := f.offsets[dst.Name]
		g.insnf("MOVD %s, %d(RSP)", reg, off)
	case AddrGlobal:
		g.insnf("MOVD %s, gaston_%s(SB)", reg, dst.Name)
	default:
		g.insn("// emit_store: unsupported dst kind")
	}
}

// ── FP load / store helpers ───────────────────────────────────────────────────

// emit_fp_load loads an FP value into fpreg (e.g. "F0").
// Stack slots for FP values are the same 8-byte slots used for integers —
// only the instruction differs (FMOVD vs MOVD).
func (g *arm64Gen) emit_fp_load(f *frame, addr IRAddr, fpreg string) {
	switch addr.Kind {
	case AddrFConst:
		g.insnf("FMOVD gaston_%s(SB), %s", addr.Name, fpreg)
	case AddrTemp, AddrLocal:
		off, ok := f.offsets[addr.Name]
		if !ok {
			g.insnf("// BUG: no offset for FP %s", addr.Name)
			return
		}
		g.insnf("FMOVD %d(RSP), %s", off, fpreg)
	case AddrGlobal:
		g.insnf("FMOVD gaston_%s(SB), %s", addr.Name, fpreg)
	default:
		g.insn("// emit_fp_load: AddrNone")
	}
}

// emit_fp_store stores fpreg (e.g. "F0") into an FP stack/global slot.
func (g *arm64Gen) emit_fp_store(f *frame, fpreg string, dst IRAddr) {
	switch dst.Kind {
	case AddrTemp, AddrLocal:
		off := f.offsets[dst.Name]
		g.insnf("FMOVD %s, %d(RSP)", fpreg, off)
	case AddrGlobal:
		g.insnf("FMOVD %s, gaston_%s(SB)", fpreg, dst.Name)
	default:
		g.insn("// emit_fp_store: unsupported dst kind")
	}
}

// ── FP arithmetic / comparison ────────────────────────────────────────────────

// emitFPArith emits: Dst = Src1 op Src2 using F0, F1.
// Plan 9 ARM64 ternary form: OP Fm, Fn, Fd  means  Fd = Fn OP Fm
func (g *arm64Gen) emitFPArith(f *frame, q Quad, op string) {
	g.emit_fp_load(f, q.Src1, "F0") // F0 = Src1
	g.emit_fp_load(f, q.Src2, "F1") // F1 = Src2
	g.insnf("%s F1, F0, F0", op)    // F0 = F0 op F1
	g.emit_fp_store(f, "F0", q.Dst)
}

// emitFPCmpBool emits: Dst = (Src1 bop Src2) as integer 0 or 1.
// FCMPD F1, F0 computes F0 − F1 and sets NZCV.
func (g *arm64Gen) emitFPCmpBool(f *frame, fn *IRFunc, q Quad, bop string) {
	g.emit_fp_load(f, q.Src1, "F0")
	g.emit_fp_load(f, q.Src2, "F1")
	g.insn("FCMPD F1, F0")

	trueL := g.newCmpLabel(fn)
	endL := g.newCmpLabel(fn)

	g.insnf("%s %s", bop, trueL)
	g.insn("MOVD $0, R0")
	g.insnf("B %s", endL)
	g.linef("%s:", trueL)
	g.insn("MOVD $1, R0")
	g.linef("%s:", endL)
	g.emit_store(f, "R0", q.Dst)
}

// ── arithmetic ───────────────────────────────────────────────────────────────

// emitArith emits: Dst = Src1 op Src2 using R0, R1.
// Plan 9 ARM64: OP Rm, Rn, Rd  means  Rd = Rn OP Rm
func (g *arm64Gen) emitArith(f *frame, q Quad, op string) {
	g.emit_load(f, q.Src1, "R0") // R0 = Src1
	g.emit_load(f, q.Src2, "R1") // R1 = Src2
	g.insnf("%s R1, R0, R0", op) // R0 = R0 op R1
	g.emit_store(f, "R0", q.Dst)
}

// emitMod emits: Dst = Src1 % Src2 using SDIV + MUL + SUB.
func (g *arm64Gen) emitMod(f *frame, q Quad) {
	g.emit_load(f, q.Src1, "R0")  // R0 = a
	g.emit_load(f, q.Src2, "R1")  // R1 = b
	g.insn("SDIV R1, R0, R2")     // R2 = a / b (signed)
	g.insn("MUL  R1, R2, R2")     // R2 = quotient * b
	g.insn("SUB  R2, R0, R0")     // R0 = a - quotient*b
	g.emit_store(f, "R0", q.Dst)
}

// emitUMod emits: Dst = Src1 % Src2 (unsigned) using UDIV + MUL + SUB.
func (g *arm64Gen) emitUMod(f *frame, q Quad) {
	g.emit_load(f, q.Src1, "R0")  // R0 = a
	g.emit_load(f, q.Src2, "R1")  // R1 = b
	g.insn("UDIV R1, R0, R2")     // R2 = a / b (unsigned)
	g.insn("MUL  R1, R2, R2")     // R2 = quotient * b
	g.insn("SUB  R2, R0, R0")     // R0 = a - quotient*b
	g.emit_store(f, "R0", q.Dst)
}

// ── comparisons ──────────────────────────────────────────────────────────────

// emitCmpBool emits: Dst = (Src1 branchOp Src2) as 0 or 1.
//
// After CMP R1, R0 (computes R0 − R1):
//   BLT → true if R0 < R1  (Src1 < Src2)
//   BLE → true if R0 ≤ R1
//   etc.
func (g *arm64Gen) emitCmpBool(f *frame, fn *IRFunc, q Quad, bop string) {
	g.emit_load(f, q.Src1, "R0")
	g.emit_load(f, q.Src2, "R1")
	g.insn("CMP R1, R0")

	trueL := g.newCmpLabel(fn)
	endL := g.newCmpLabel(fn)

	g.insnf("%s %s", bop, trueL)
	g.insn("MOVD $0, R0")
	g.insnf("B %s", endL)
	g.linef("%s:", trueL)
	g.insn("MOVD $1, R0")
	g.linef("%s:", endL)
	g.emit_store(f, "R0", q.Dst)
}

// ── array access ──────────────────────────────────────────────────────────────

// structBase loads the base address of a struct into reg, distinguishing two cases:
//  - isArrBase (struct local — storage is inline in the frame): ADD $off, RSP, reg
//  - everything else (temp / pointer slot that HOLDS the address): MOVD off(RSP), reg
// Used by IRStructCopy and emitStructReturn where the IRAddr may be a pointer-valued temp
// produced by genExpr(KindFieldAccess, TypeStruct) rather than a direct storage slot.
func (g *arm64Gen) structBase(f *frame, addr IRAddr, reg string) {
	switch addr.Kind {
	case AddrGlobal:
		g.insnf("MOVD $gaston_%s(SB), %s", addr.Name, reg)
	case AddrLocal, AddrTemp:
		off := f.offsets[addr.Name]
		if f.isArrBase[addr.Name] {
			g.insnf("ADD $%d, RSP, %s", off, reg) // struct inline in frame → compute address
		} else {
			g.insnf("MOVD %d(RSP), %s", off, reg) // slot holds a pointer value → load it
		}
	}
}

// arrayBase loads the base address of an array into reg.
// For global arrays: MOVD $gaston_name(SB), reg
// For local arrays:  ADD $offset, RSP, reg
// For array params:  MOVD offset(RSP), reg  (load stored pointer)
func (g *arm64Gen) arrayBase(f *frame, addr IRAddr, reg string) {
	switch addr.Kind {
	case AddrGlobal:
		g.insnf("MOVD $gaston_%s(SB), %s", addr.Name, reg)
	case AddrLocal, AddrTemp:
		off := f.offsets[addr.Name]
		if f.isArrPtr[addr.Name] {
			// Array parameter: the slot holds a pointer.
			g.insnf("MOVD %d(RSP), %s", off, reg)
		} else {
			// Local array: compute its address on the stack.
			g.insnf("ADD $%d, RSP, %s", off, reg)
		}
	}
}

// emitArrayLoad emits: Dst = Src1[Src2]
func (g *arm64Gen) emitArrayLoad(f *frame, q Quad) {
	g.arrayBase(f, q.Src1, "R0")  // R0 = base address
	g.emit_load(f, q.Src2, "R1")  // R1 = index
	g.insn("LSL $3, R1, R1")      // R1 = index * 8
	g.insn("ADD R1, R0, R0")      // R0 = base + index*8
	if isFPType(q.TypeHint) {
		g.insn("FMOVD (R0), F0")         // F0 = *R0 (FP load)
		g.emit_fp_store(f, "F0", q.Dst)
	} else {
		g.insn("MOVD (R0), R0")          // R0 = *R0
		g.emit_store(f, "R0", q.Dst)
	}
}

// emitArrayStore emits: Dst[Src1] = Src2
func (g *arm64Gen) emitArrayStore(f *frame, q Quad) {
	g.arrayBase(f, q.Dst, "R0")   // R0 = base address
	g.emit_load(f, q.Src1, "R1")  // R1 = index
	g.insn("LSL $3, R1, R1")      // R1 = index * 8
	g.insn("ADD R1, R0, R0")      // R0 = base + index*8
	if isFPType(q.TypeHint) {
		g.emit_fp_load(f, q.Src2, "F0") // F0 = value
		g.insn("FMOVD F0, (R0)")        // *R0 = F0 (FP store)
	} else {
		g.emit_load(f, q.Src2, "R2")  // R2 = value
		g.insn("MOVD R2, (R0)")       // *R0 = R2
	}
}

// emitCharArrayLoad emits: Dst = Src1[Src2]  (char* byte-level load, no stride scaling)
func (g *arm64Gen) emitCharArrayLoad(f *frame, q Quad) {
	g.arrayBase(f, q.Src1, "R0")  // R0 = base address
	g.emit_load(f, q.Src2, "R1")  // R1 = byte index (no scaling)
	g.insn("ADD R1, R0, R0")      // R0 = base + index
	g.insn("MOVBU (R0), R0")      // R0 = byte (zero-extended)
	g.emit_store(f, "R0", q.Dst)
}

// emitCharArrayStore emits: Dst[Src1] = Src2  (char* byte-level store, no stride scaling)
func (g *arm64Gen) emitCharArrayStore(f *frame, q Quad) {
	g.arrayBase(f, q.Dst, "R0")   // R0 = base address
	g.emit_load(f, q.Src1, "R1")  // R1 = byte index (no scaling)
	g.insn("ADD R1, R0, R0")      // R0 = base + index
	g.emit_load(f, q.Src2, "R2")  // R2 = value (low byte stored)
	g.insn("MOVB R2, (R0)")       // store byte
}

// emitAddrOf emits: Dst = &Src1  (base address of array)
func (g *arm64Gen) emitAddrOf(f *frame, q Quad) {
	g.arrayBase(f, q.Src1, "R0")
	g.emit_store(f, "R0", q.Dst)
}

// ── function calls ────────────────────────────────────────────────────────────

// emitCall emits argument moves and a CALL instruction, storing the result.
// Integer params go into R0–R7; FP params go into F0–F7 (separate counters,
// per AAPCS64: each class has its own next-register index).
func (g *arm64Gen) emitCall(f *frame, fn *IRFunc, q Quad) {
	// __va_start is a compiler builtin: returns RSP + (16 + 8*nRegSlots),
	// where nRegSlots counts the actual integer registers consumed by named params
	// (≤16-byte struct params consume 2 registers; >16-byte consume 1 pointer).
	if q.Extra == "__va_start" {
		g.pendingParams = g.pendingParams[:0]
		regSlots := 0
		for i := range fn.Params {
			if i < len(fn.ParamType) && fn.ParamType[i] == TypeStruct {
				tag := ""
				if i < len(fn.ParamStructTag) {
					tag = fn.ParamStructTag[i]
				}
				size := 0
				if sd, ok := g.structDefs[tag]; ok {
					size = sd.SizeBytes(g.structDefs)
				}
				if size > 8 && size <= 16 {
					regSlots += 2
				} else {
					regSlots++
				}
			} else if i < len(fn.ParamType) && !isFPType(fn.ParamType[i]) {
				regSlots++
			}
		}
		offset := 16 + 8*regSlots
		g.insnf("ADD $%d, RSP, R0", offset)
		if q.Dst.Kind != AddrNone {
			g.emit_store(f, "R0", q.Dst)
		}
		return
	}

	iIdx, fIdx := 0, 0
	for _, p := range g.pendingParams {
		if p.isStruct {
			sd := g.structDefs[p.structTag]
			size := 0
			if sd != nil {
				size = sd.SizeBytes(g.structDefs)
			}
			switch {
			case size <= 8:
				g.structBase(f, p.addr, "R9")
				g.insnf("MOVD (R9), R%d", iIdx)
				iIdx++
			case size <= 16:
				g.structBase(f, p.addr, "R9")
				g.insnf("MOVD (R9), R%d", iIdx)
				g.insnf("MOVD 8(R9), R%d", iIdx+1)
				iIdx += 2
			default:
				// p.addr is inline frame storage; its address IS the caller-owned copy
				g.structBase(f, p.addr, fmt.Sprintf("R%d", iIdx))
				iIdx++
			}
		} else if p.isFP {
			if fIdx >= 8 {
				g.insn("// WARNING: >8 FP args, extra dropped")
				continue
			}
			g.emit_fp_load(f, p.addr, fmt.Sprintf("F%d", fIdx))
			fIdx++
		} else {
			if iIdx >= 8 {
				g.insn("// WARNING: >8 int args, extra dropped")
				continue
			}
			g.emit_load(f, p.addr, fmt.Sprintf("R%d", iIdx))
			iIdx++
		}
	}
	g.pendingParams = g.pendingParams[:0]

	// Struct-returning call: set X8 (>16 bytes) or unpack X0/X1 after BL (≤16 bytes).
	if q.TypeHint == TypeStruct && q.StructTag != "" {
		sd := g.structDefs[q.StructTag]
		size := 0
		if sd != nil {
			size = sd.SizeBytes(g.structDefs)
		}
		if size > 16 {
			// X8 = destination address; callee writes through it.
			g.arrayBase(f, q.Src2, "R8")
		}
		g.insnf("CALL gaston_%s(SB)", q.Extra)
		if size <= 8 {
			g.arrayBase(f, q.Src2, "R9") // recompute dest (X8–X17 may be clobbered)
			g.insn("MOVD R0, (R9)")
		} else if size <= 16 {
			g.arrayBase(f, q.Src2, "R9")
			g.insn("MOVD R0, (R9)")
			g.insn("MOVD R1, 8(R9)")
		}
		// size > 16: callee wrote through X8 already; nothing to do.
		return
	}

	switch q.Extra {
	case "input":
		g.insn("CALL gaston_input(SB)")
	case "output":
		g.insn("CALL gaston_output(SB)")
	case "print_char":
		g.insn("CALL gaston_print_char(SB)")
	case "print_string":
		g.insn("CALL gaston_print_string(SB)")
	default:
		g.insnf("CALL gaston_%s(SB)", q.Extra)
	}

	if q.Dst.Kind != AddrNone {
		g.emit_store(f, "R0", q.Dst)
	}
}

// emitEpilogue restores the frame record, deallocates the frame, and returns.
func (g *arm64Gen) emitEpilogue(f *frame) {
	g.insn("MOVD 0(RSP), R29")   // restore FP
	g.insn("MOVD 8(RSP), R30")   // restore LR
	g.insnf("ADD $%d, RSP, RSP", f.frameSize)
	g.insn("RET")
}

// emitStructReturn handles IRReturn when TypeHint == TypeStruct.
// q.Src1 names the local struct variable to return; q.StructTag names the type.
// AAPCS64 rules:
//   ≤  8 bytes → X0 = first 8-byte word
//   ≤ 16 bytes → X0 = first word, X1 = second word
//   > 16 bytes → caller put destination in X8; copy all words through it
func (g *arm64Gen) emitStructReturn(f *frame, q Quad) {
	sd := g.structDefs[q.StructTag]
	size := 0
	if sd != nil {
		size = sd.SizeBytes(g.structDefs)
	}
	// R9 = base address of source struct
	g.structBase(f, q.Src1, "R9")
	switch {
	case size <= 8:
		g.insn("MOVD (R9), R0")
	case size <= 16:
		g.insn("MOVD (R9), R0")
		g.insn("MOVD 8(R9), R1")
	default:
		// Reload the caller's destination pointer that was saved on entry.
		if off, ok := f.offsets["__x8_save"]; ok {
			g.insnf("MOVD %d(RSP), R8", off)
		}
		numWords := (size + 7) / 8
		for i := 0; i < numWords; i++ {
			g.insnf("MOVD %d(R9), R10", i*8)
			g.insnf("MOVD R10, %d(R8)", i*8)
		}
	}
	g.emitEpilogue(f)
}

// ── utilities ─────────────────────────────────────────────────────────────────

func paramSig(fn *IRFunc) string {
	if len(fn.Params) == 0 {
		return "void"
	}
	parts := make([]string, len(fn.Params))
	for i, name := range fn.Params {
		if i < len(fn.ParamType) && fn.ParamType[i] == TypeIntArray {
			parts[i] = "int " + name + "[]"
		} else {
			parts[i] = "int " + name
		}
	}
	return strings.Join(parts, ", ")
}
