// Code generated by goyacc -o cmd/gaston/parser.go cmd/gaston/grammar.y. DO NOT EDIT.

//line cmd/gaston/grammar.y:7
package main

import __yyfmt__ "fmt"

//line cmd/gaston/grammar.y:7

//line cmd/gaston/grammar.y:10
type yySymType struct {
	yys   int
	ival  int
	sval  string
	node  *Node
	nodes []*Node
	typ   TypeKind
}

const NUM = 57346
const ID = 57347
const INT = 57348
const VOID = 57349
const IF = 57350
const ELSE = 57351
const WHILE = 57352
const RETURN = 57353
const LE = 57354
const GE = 57355
const EQ = 57356
const NE = 57357
const LOWER_THAN_ELSE = 57358

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUM",
	"ID",
	"INT",
	"VOID",
	"IF",
	"ELSE",
	"WHILE",
	"RETURN",
	"LE",
	"GE",
	"EQ",
	"NE",
	"LOWER_THAN_ELSE",
	"';'",
	"'['",
	"']'",
	"'('",
	"')'",
	"','",
	"'{'",
	"'}'",
	"'='",
	"'<'",
	"'>'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line cmd/gaston/grammar.y:231

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 122

var yyAct = [...]int8{
	41, 35, 46, 51, 50, 61, 49, 66, 69, 70,
	71, 75, 76, 54, 48, 72, 73, 43, 95, 44,
	45, 67, 68, 72, 73, 6, 42, 4, 26, 52,
	22, 94, 26, 34, 37, 54, 48, 11, 12, 43,
	13, 44, 45, 18, 92, 91, 60, 90, 42, 54,
	48, 52, 58, 77, 26, 33, 25, 32, 78, 79,
	54, 48, 81, 82, 85, 52, 27, 87, 87, 21,
	88, 86, 62, 59, 63, 57, 52, 87, 89, 93,
	11, 12, 99, 30, 20, 28, 80, 56, 24, 7,
	8, 19, 17, 96, 97, 19, 98, 55, 23, 10,
	14, 100, 3, 74, 65, 9, 64, 84, 83, 53,
	47, 40, 39, 38, 36, 31, 29, 16, 15, 2,
	5, 1,
}

var yyPact = [...]int16{
	83, -1000, 83, -1000, -1000, -1000, 94, -1000, -1000, -1000,
	20, -1000, 96, 85, 65, 48, 8, -1000, -1000, 93,
	71, 5, 89, 67, -1000, -1000, -1000, -1000, 64, 83,
	-1000, 9, -1000, 92, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 70, -1000, 55, 32, 56, -20, -1000, 54, -5,
	-19, -1000, 45, -1000, -1000, 63, -1000, 45, 45, -1000,
	69, 45, 45, 45, 45, 45, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 45, -1000, -1000, 26, 24, 23,
	-1000, -1000, 60, 10, -4, -1000, -13, -1000, -19, -1000,
	-1000, 31, 31, -1000, -1000, 45, 73, -1000, -1000, 31,
	-1000,
}

var yyPgo = [...]int8{
	0, 121, 102, 27, 120, 119, 118, 117, 43, 34,
	116, 115, 1, 114, 113, 112, 111, 0, 2, 110,
	6, 4, 3, 109, 108, 107, 25, 106, 104, 103,
}

var yyR1 = [...]int8{
	0, 1, 5, 5, 2, 2, 3, 3, 26, 26,
	4, 6, 6, 7, 7, 8, 8, 9, 10, 10,
	11, 11, 12, 12, 12, 12, 12, 13, 13, 14,
	14, 15, 16, 16, 17, 17, 18, 18, 19, 19,
	27, 27, 27, 27, 27, 27, 20, 20, 28, 28,
	21, 21, 29, 29, 22, 22, 22, 22, 23, 24,
	24, 25, 25,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 1, 1, 3, 6, 1, 1,
	6, 1, 1, 3, 1, 2, 4, 4, 2, 0,
	2, 0, 1, 1, 1, 1, 1, 2, 1, 5,
	7, 5, 2, 3, 3, 1, 1, 4, 3, 1,
	1, 1, 1, 1, 1, 1, 3, 1, 1, 1,
	3, 1, 1, 1, 3, 1, 1, 1, 4, 1,
	0, 3, 1,
}

var yyChk = [...]int16{
	-1000, -1, -5, -2, -3, -4, -26, 6, 7, -2,
	5, 17, 18, 20, 4, -6, -7, 7, -8, 6,
	19, 21, 22, 5, 17, -9, 23, -8, 18, -10,
	19, -11, -3, -26, 24, -12, -13, -9, -14, -15,
	-16, -17, 17, 8, 10, 11, -18, -19, 5, -20,
	-21, -22, 20, -23, 4, 5, 17, 20, 20, 17,
	-17, 25, 18, 20, -27, -28, 12, 26, 27, 13,
	14, 15, 28, 29, -29, 30, 31, -17, -17, -17,
	17, -17, -17, -24, -25, -17, -20, -18, -21, -22,
	21, 21, 21, 19, 21, 22, -12, -12, -17, 9,
	-12,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 4, 5, 0, 8, 9, 2,
	0, 6, 0, 0, 0, 0, 11, 12, 14, 0,
	0, 0, 0, 15, 7, 10, 19, 13, 0, 21,
	16, 0, 18, 0, 17, 20, 22, 23, 24, 25,
	26, 0, 28, 0, 0, 0, 55, 35, 36, 39,
	47, 51, 0, 56, 57, 0, 27, 0, 0, 32,
	0, 0, 0, 60, 0, 0, 40, 41, 42, 43,
	44, 45, 48, 49, 0, 52, 53, 0, 0, 0,
	33, 34, 0, 0, 59, 62, 38, 55, 46, 50,
	54, 0, 0, 37, 58, 0, 29, 31, 61, 0,
	30,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	20, 21, 30, 28, 22, 29, 3, 31, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 17,
	26, 25, 27, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 18, 3, 19, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 23, 3, 24,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:47
		{
			yylex.(*lexer).result = &Node{Kind: KindProgram, Children: yyDollar[1].nodes}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:52
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:54
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:58
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:59
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:64
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
		}
	case 7:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:66
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[2].sval, Val: yyDollar[4].ival}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:70
		{
			yyVAL.typ = TypeInt
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:71
		{
			yyVAL.typ = TypeVoid
		}
	case 10:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:76
		{
			n := &Node{Kind: KindFunDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
			n.Children = append(yyDollar[4].nodes, yyDollar[6].node)
			yyVAL.node = n
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:84
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:85
		{
			yyVAL.nodes = nil
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:90
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:92
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:97
		{
			yyVAL.node = &Node{Kind: KindParam, Type: TypeInt, Name: yyDollar[2].sval}
		}
	case 16:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:99
		{
			yyVAL.node = &Node{Kind: KindParam, Type: TypeIntArray, Name: yyDollar[2].sval}
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:104
		{
			yyVAL.node = &Node{Kind: KindCompound, Children: append(yyDollar[2].nodes, yyDollar[3].nodes...)}
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:109
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 19:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:111
		{
			yyVAL.nodes = nil
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:116
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 21:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:118
		{
			yyVAL.nodes = nil
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:122
		{
			yyVAL.node = yyDollar[1].node
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:123
		{
			yyVAL.node = yyDollar[1].node
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:124
		{
			yyVAL.node = yyDollar[1].node
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:125
		{
			yyVAL.node = yyDollar[1].node
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:126
		{
			yyVAL.node = yyDollar[1].node
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:130
		{
			yyVAL.node = &Node{Kind: KindExprStmt, Children: []*Node{yyDollar[1].node}}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:131
		{
			yyVAL.node = &Node{Kind: KindExprStmt}
		}
	case 29:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:136
		{
			yyVAL.node = &Node{Kind: KindSelection, Children: []*Node{yyDollar[3].node, yyDollar[5].node}}
		}
	case 30:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:138
		{
			yyVAL.node = &Node{Kind: KindSelection, Children: []*Node{yyDollar[3].node, yyDollar[5].node, yyDollar[7].node}}
		}
	case 31:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:143
		{
			yyVAL.node = &Node{Kind: KindIteration, Children: []*Node{yyDollar[3].node, yyDollar[5].node}}
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:148
		{
			yyVAL.node = &Node{Kind: KindReturn}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:150
		{
			yyVAL.node = &Node{Kind: KindReturn, Children: []*Node{yyDollar[2].node}}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:155
		{
			yyVAL.node = &Node{Kind: KindAssign, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:157
		{
			yyVAL.node = yyDollar[1].node
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:162
		{
			yyVAL.node = &Node{Kind: KindVar, Name: yyDollar[1].sval}
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:164
		{
			yyVAL.node = &Node{Kind: KindArrayVar, Name: yyDollar[1].sval, Children: []*Node{yyDollar[3].node}}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:169
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:171
		{
			yyVAL.node = yyDollar[1].node
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:175
		{
			yyVAL.sval = "<="
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:176
		{
			yyVAL.sval = "<"
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:177
		{
			yyVAL.sval = ">"
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:178
		{
			yyVAL.sval = ">="
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:179
		{
			yyVAL.sval = "=="
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:180
		{
			yyVAL.sval = "!="
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:185
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:187
		{
			yyVAL.node = yyDollar[1].node
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:191
		{
			yyVAL.sval = "+"
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:192
		{
			yyVAL.sval = "-"
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:197
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:199
		{
			yyVAL.node = yyDollar[1].node
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:203
		{
			yyVAL.sval = "*"
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:204
		{
			yyVAL.sval = "/"
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:208
		{
			yyVAL.node = yyDollar[2].node
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:209
		{
			yyVAL.node = yyDollar[1].node
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:210
		{
			yyVAL.node = yyDollar[1].node
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:211
		{
			yyVAL.node = &Node{Kind: KindNum, Val: yyDollar[1].ival}
		}
	case 58:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:216
		{
			yyVAL.node = &Node{Kind: KindCall, Name: yyDollar[1].sval, Children: yyDollar[3].nodes}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:220
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 60:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:221
		{
			yyVAL.nodes = nil
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:226
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:228
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	}
	goto yystack /* stack new state and value */
}
