// Code generated by goyacc -o cmd/gaston/parser.go cmd/gaston/grammar.y. DO NOT EDIT.

//line cmd/gaston/grammar.y:8
package main

import __yyfmt__ "fmt"

//line cmd/gaston/grammar.y:8

//line cmd/gaston/grammar.y:11
type yySymType struct {
	yys   int
	ival  int
	fval  float64
	sval  string
	node  *Node
	nodes []*Node
	typ   TypeKind
}

const NUM = 57346
const CHAR_LIT = 57347
const FNUM = 57348
const ID = 57349
const STRING_LIT = 57350
const INT = 57351
const VOID = 57352
const IF = 57353
const ELSE = 57354
const WHILE = 57355
const RETURN = 57356
const FOR = 57357
const DO = 57358
const BREAK = 57359
const CONTINUE = 57360
const CONST = 57361
const CHAR = 57362
const EXTERN = 57363
const GOTO = 57364
const LONG = 57365
const UNSIGNED = 57366
const SHORT = 57367
const FLOAT = 57368
const DOUBLE = 57369
const STRUCT = 57370
const SIZEOF = 57371
const ENUM = 57372
const UNION = 57373
const TYPEDEF = 57374
const STATIC = 57375
const TYPENAME = 57376
const LE = 57377
const GE = 57378
const EQ = 57379
const NE = 57380
const LSHIFT = 57381
const RSHIFT = 57382
const INC = 57383
const DEC = 57384
const PLUSEQ = 57385
const MINUSEQ = 57386
const STAREQ = 57387
const DIVEQ = 57388
const MODEQ = 57389
const ARROW = 57390
const ELLIPSIS = 57391
const LOWER_THAN_ELSE = 57392

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUM",
	"CHAR_LIT",
	"FNUM",
	"ID",
	"STRING_LIT",
	"INT",
	"VOID",
	"IF",
	"ELSE",
	"WHILE",
	"RETURN",
	"FOR",
	"DO",
	"BREAK",
	"CONTINUE",
	"CONST",
	"CHAR",
	"EXTERN",
	"GOTO",
	"LONG",
	"UNSIGNED",
	"SHORT",
	"FLOAT",
	"DOUBLE",
	"STRUCT",
	"SIZEOF",
	"ENUM",
	"UNION",
	"TYPEDEF",
	"STATIC",
	"TYPENAME",
	"LE",
	"GE",
	"EQ",
	"NE",
	"LSHIFT",
	"RSHIFT",
	"INC",
	"DEC",
	"PLUSEQ",
	"MINUSEQ",
	"STAREQ",
	"DIVEQ",
	"MODEQ",
	"ARROW",
	"ELLIPSIS",
	"LOWER_THAN_ELSE",
	"';'",
	"'['",
	"']'",
	"'*'",
	"'('",
	"')'",
	"','",
	"'='",
	"'{'",
	"'}'",
	"':'",
	"'.'",
	"'&'",
	"'|'",
	"'^'",
	"'<'",
	"'>'",
	"'+'",
	"'-'",
	"'/'",
	"'%'",
	"'!'",
	"'~'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line cmd/gaston/grammar.y:577

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 105,
	56, 63,
	-2, 44,
}

const yyPrivate = 57344

const yyLast = 662

var yyAct = [...]int16{
	371, 314, 409, 107, 12, 359, 12, 312, 361, 106,
	5, 4, 91, 72, 90, 104, 103, 83, 120, 36,
	37, 38, 88, 41, 119, 92, 86, 181, 94, 96,
	95, 370, 97, 178, 179, 373, 149, 374, 377, 375,
	376, 378, 379, 182, 183, 175, 380, 242, 176, 258,
	150, 62, 82, 102, 392, 152, 153, 154, 155, 156,
	157, 158, 149, 272, 274, 121, 173, 174, 121, 40,
	418, 140, 151, 273, 139, 372, 150, 138, 84, 93,
	128, 129, 131, 258, 358, 346, 297, 101, 130, 126,
	170, 171, 172, 98, 184, 287, 99, 100, 63, 192,
	265, 429, 160, 64, 164, 167, 168, 169, 173, 174,
	159, 425, 212, 196, 59, 198, 160, 160, 160, 213,
	416, 54, 202, 121, 185, 186, 187, 55, 188, 203,
	121, 215, 170, 171, 172, 165, 166, 415, 205, 390,
	49, 50, 49, 50, 52, 205, 53, 51, 53, 51,
	219, 218, 236, 225, 354, 237, 238, 239, 240, 241,
	199, 60, 113, 112, 345, 396, 61, 200, 381, 114,
	132, 133, 74, 335, 134, 62, 246, 249, 245, 160,
	160, 160, 334, 303, 301, 244, 298, 243, 30, 296,
	250, 256, 291, 286, 253, 160, 252, 201, 160, 191,
	257, 268, 260, 59, 270, 395, 251, 94, 96, 95,
	89, 97, 20, 21, 281, 32, 33, 394, 175, 75,
	76, 176, 63, 22, 348, 330, 23, 25, 24, 26,
	27, 254, 102, 269, 255, 32, 33, 28, 278, 190,
	264, 143, 137, 294, 58, 20, 21, 277, 414, 384,
	60, 391, 262, 206, 193, 388, 22, 84, 93, 23,
	25, 24, 26, 27, 122, 344, 101, 123, 343, 331,
	28, 347, 98, 315, 144, 99, 100, 94, 96, 95,
	370, 97, 135, 68, 373, 279, 374, 377, 375, 376,
	378, 379, 66, 332, 276, 380, 211, 260, 333, 263,
	207, 194, 102, 304, 56, 318, 339, 319, 320, 78,
	295, 288, 342, 338, 337, 94, 96, 95, 89, 97,
	306, 145, 284, 266, 372, 232, 231, 84, 93, 136,
	69, 217, 258, 357, 315, 147, 101, 146, 355, 65,
	102, 261, 98, 221, 220, 99, 100, 175, 386, 428,
	315, 57, 305, 424, 417, 413, 412, 405, 404, 401,
	400, 393, 398, 389, 385, 84, 93, 356, 353, 352,
	350, 349, 329, 327, 101, 326, 325, 323, 399, 322,
	98, 316, 397, 99, 100, 311, 94, 96, 95, 89,
	97, 310, 292, 290, 289, 407, 408, 410, 406, 94,
	96, 95, 89, 97, 285, 283, 282, 280, 271, 267,
	233, 102, 229, 227, 224, 210, 148, 141, 410, 422,
	421, 419, 420, 124, 102, 410, 117, 427, 45, 426,
	43, 411, 423, 79, 44, 430, 84, 93, 80, 47,
	402, 81, 46, 387, 48, 101, 383, 382, 324, 161,
	93, 98, 321, 309, 99, 100, 308, 403, 101, 20,
	21, 307, 300, 299, 98, 275, 235, 99, 100, 234,
	22, 230, 228, 23, 25, 24, 26, 27, 122, 20,
	21, 123, 73, 223, 28, 222, 209, 208, 195, 109,
	22, 189, 142, 23, 25, 24, 26, 27, 108, 127,
	125, 118, 116, 115, 28, 111, 20, 21, 110, 77,
	204, 70, 67, 35, 34, 351, 109, 22, 317, 328,
	23, 25, 24, 26, 27, 108, 20, 21, 293, 226,
	216, 28, 214, 197, 163, 180, 15, 22, 17, 177,
	23, 25, 24, 26, 27, 13, 259, 18, 14, 19,
	16, 28, 20, 21, 3, 162, 248, 29, 247, 87,
	85, 369, 15, 22, 368, 367, 23, 25, 24, 26,
	27, 340, 20, 105, 341, 366, 16, 28, 365, 364,
	363, 362, 109, 22, 20, 21, 23, 25, 24, 26,
	27, 108, 360, 336, 302, 22, 313, 28, 23, 25,
	24, 26, 27, 122, 20, 21, 123, 11, 71, 28,
	10, 9, 8, 31, 2, 22, 20, 21, 23, 25,
	24, 26, 27, 42, 7, 6, 1, 22, 0, 28,
	23, 25, 24, 26, 27, 39, 20, 21, 0, 0,
	0, 28, 0, 0, 0, 0, 0, 22, 0, 0,
	23, 25, 24, 26, 27, 0, 0, 0, 0, 0,
	0, 28,
}

var yyPact = [...]int16{
	517, -1000, 517, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 181, 507, 506, 627, 627, 607, 10, 595,
	-1000, -1000, -1000, 407, 425, 419, -1000, -1000, -1000, -1000,
	89, 70, 297, 190, 107, 44, 285, 505, 276, 504,
	475, 165, 502, -1000, -1000, -1000, 286, -1000, 424, -1000,
	434, 382, 563, 501, -1000, 498, 111, 496, 495, 375,
	494, 575, 372, 493, 575, 492, 22, 30, 119, 275,
	188, 17, -1000, 13, 366, 485, 187, 267, -1000, -1000,
	284, 282, 365, 14, 395, -1000, -1000, -1000, 69, 166,
	-35, -27, -1000, 382, -1000, -1000, -1000, -1000, 395, 395,
	395, 484, 184, 143, 42, -1000, -1000, 247, 481, 627,
	-1000, -1000, 529, -1000, 382, 109, 141, -1000, 71, 450,
	-1000, 246, 480, 479, -1000, 364, 236, 61, 528, -1000,
	382, 526, -1000, 278, 563, 292, 478, 476, 363, 475,
	525, -1000, 362, 465, 361, 464, 274, 359, -1000, 462,
	459, 382, -1000, -1000, 382, 382, 382, 382, 382, -11,
	-12, 395, 395, 395, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 382, 382, 395, -1000, -1000,
	395, -1000, -1000, -1000, 140, -1000, -1000, -1000, -1000, 295,
	203, -10, 497, 289, 245, 186, 46, 270, 358, -1000,
	382, 178, -1000, 382, 357, -1000, 12, 458, 240, 231,
	-1000, 356, -1000, 382, 355, 354, 269, 353, 137, 38,
	258, -1000, 343, 342, -1000, -1000, -1000, -1000, 136, -1000,
	341, 524, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 382, -1000, 27, -35, 257, 133, 29, -1000,
	-27, -1000, -1000, 130, 456, 455, 128, -1000, -1000, 127,
	-1000, 299, 268, 454, 449, 446, 340, -1000, 334, 627,
	330, -1000, -1000, 514, 252, 256, 445, 328, 326, 441,
	-1000, 325, -1000, -1000, 324, -1000, 322, 470, 321, -1000,
	-1000, 170, -1000, 216, -1000, 241, -1000, 382, -1000, 126,
	117, -1000, 543, -10, 215, -1000, 212, -1000, -1000, -1000,
	-1000, -1000, 108, 28, -1000, 217, -1000, 320, 319, -1000,
	511, 318, -1000, -1000, 317, -1000, -1000, -1000, 98, -1000,
	627, 316, 382, -1000, -1000, -1000, 24, -1000, -1000, 161,
	440, 439, -1000, 197, -1000, 313, 627, 436, -1000, -1000,
	-1000, 202, -1000, -1000, 312, 83, -1000, 198, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-7, 310, -1000, 162, 150, 110, 273, 311, 309, 308,
	433, 91, 196, 168, 453, -1000, -1000, -1000, 307, -1000,
	306, -1000, 273, -1000, 382, 382, 382, 418, -1000, 305,
	-1000, -1000, 304, 195, -1000, -1000, -1000, 81, 64, 303,
	-1000, 15, -1000, -1000, -1000, 273, 273, 382, 382, 420,
	-1000, 302, 55, 273, 382, 298, -1000, 45, -1000, 273,
	-1000,
}

var yyPgo = [...]int16{
	0, 626, 625, 554, 11, 10, 624, 614, 16, 15,
	613, 612, 24, 611, 610, 608, 607, 7, 596, 18,
	9, 8, 17, 13, 1, 594, 593, 5, 592, 581,
	580, 579, 578, 575, 565, 564, 561, 2, 0, 26,
	560, 22, 14, 12, 25, 559, 558, 556, 3, 555,
	539, 535, 534,
}

var yyR1 = [...]int8{
	0, 1, 7, 7, 3, 3, 3, 3, 3, 3,
	3, 3, 6, 6, 6, 6, 6, 6, 6, 6,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 5, 48, 48, 48, 48, 48, 48, 48,
	48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
	2, 2, 8, 8, 9, 9, 9, 20, 20, 20,
	20, 20, 20, 20, 20, 21, 25, 25, 25, 10,
	10, 26, 26, 27, 27, 27, 27, 27, 27, 27,
	27, 27, 27, 27, 28, 28, 29, 29, 30, 31,
	32, 36, 34, 35, 37, 37, 33, 33, 22, 22,
	22, 22, 38, 38, 38, 38, 38, 38, 38, 38,
	38, 38, 39, 39, 39, 40, 40, 41, 41, 52,
	52, 52, 52, 52, 49, 49, 49, 49, 49, 49,
	42, 42, 50, 50, 43, 43, 51, 51, 51, 44,
	44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
	44, 44, 44, 44, 45, 46, 46, 47, 47, 11,
	13, 14, 15, 15, 23, 23, 16, 16, 16, 16,
	16, 17, 17, 18, 18, 24, 24, 24, 24, 12,
	12, 19, 19, 19, 19, 19, 19, 19, 19, 19,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 4, 6, 7, 5, 6, 6, 7, 9,
	3, 9, 6, 6, 5, 3, 7, 4, 6, 5,
	7, 4, 5, 7, 4, 5, 9, 5, 7, 4,
	6, 7, 6, 1, 1, 1, 1, 2, 1, 2,
	1, 2, 2, 3, 2, 2, 3, 1, 1, 1,
	6, 8, 1, 1, 3, 3, 1, 2, 8, 4,
	5, 3, 4, 4, 4, 4, 2, 2, 0, 3,
	3, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 2, 1, 5, 7, 5, 9,
	7, 3, 2, 2, 1, 0, 2, 3, 1, 1,
	3, 3, 3, 4, 2, 2, 3, 3, 3, 3,
	3, 1, 1, 7, 4, 3, 1, 3, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 1, 1, 1, 3, 1, 1, 1, 1, 3,
	1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
	4, 5, 5, 4, 4, 1, 0, 3, 1, 6,
	6, 5, 3, 1, 1, 3, 4, 5, 5, 6,
	10, 1, 0, 3, 1, 1, 2, 2, 3, 2,
	1, 3, 5, 5, 4, 7, 5, 4, 4, 5,
}

var yyChk = [...]int16{
	-1000, -1, -7, -3, -4, -5, -2, -6, -11, -13,
	-14, -16, -48, 28, 31, 19, 33, 21, 30, 32,
	9, 10, 20, 23, 25, 24, 26, 27, 34, -3,
	7, -10, 54, 55, 7, 7, -48, -48, -48, 28,
	59, -48, 28, 23, 9, 9, 23, 20, 25, 51,
	52, 58, 55, 57, 51, 57, 7, 54, 54, 7,
	54, 59, 7, 54, 59, 54, 7, 7, 7, 54,
	7, -15, -23, 7, 7, 54, 55, 7, 23, 9,
	4, 7, -38, -22, 54, -40, -39, -45, -41, 7,
	-42, -43, -44, 55, 4, 6, 5, 8, 69, 72,
	73, 63, 29, -8, -9, 10, -20, -48, 28, 19,
	7, 7, 52, 51, 58, 7, 7, 51, 7, -12,
	-19, -48, 28, 31, 51, 7, -12, 7, 58, 51,
	58, 52, 51, 52, 55, 7, 54, 54, 60, 57,
	58, 51, 7, 54, 7, 54, 53, 53, 51, 48,
	62, 58, 41, 42, 43, 44, 45, 46, 47, -44,
	-22, 54, -49, -52, 35, 66, 67, 36, 37, 38,
	63, 64, 65, 39, 40, 52, 55, -50, 68, 69,
	-51, 54, 70, 71, -38, -44, -44, -44, -39, 7,
	55, 56, 57, 7, 54, 7, -48, 4, -38, 51,
	58, 56, 51, 58, 60, -19, 7, 54, 7, 7,
	51, 60, 51, 58, 4, -38, 4, 53, -8, -9,
	52, 51, 7, 7, 51, -23, 4, 51, 7, 51,
	7, 52, 51, 51, 7, 7, -38, -38, -38, -38,
	-38, -38, 58, -44, -41, -42, -38, -46, -47, -38,
	-43, -44, 56, -48, 28, 31, -38, -21, 59, 49,
	-20, 52, 7, 54, 54, 54, 53, 51, -38, 55,
	-38, 51, 51, 61, 52, 7, 54, 7, 7, 54,
	51, -38, 51, 51, 53, 51, 56, 57, 53, 51,
	51, 56, 51, 4, -38, 53, 56, 57, 56, 7,
	7, 56, -25, 56, 4, 53, 52, 7, 7, 7,
	51, 51, -17, -18, -24, -48, 51, 4, 53, 51,
	52, 7, 51, 51, 7, 51, 51, 51, 49, 51,
	55, 53, 52, -38, 56, 56, -26, -4, -5, -48,
	28, 31, -21, 53, 53, 56, 57, 54, 7, 51,
	51, 4, 51, 51, 56, -17, 51, -38, 60, -27,
	-28, -21, -29, -30, -31, -32, -33, -34, -35, -36,
	7, -38, 51, 11, 13, 15, 16, 14, 17, 18,
	22, 7, 7, 7, 52, 51, -24, 7, 53, 51,
	56, 53, 61, 51, 55, 55, 55, -27, 51, -38,
	51, 51, 7, 4, 51, 51, -27, -38, -38, -37,
	-38, 13, 51, 51, 53, 56, 56, 51, 55, -27,
	-27, -37, -38, 12, 51, 56, -27, -37, 51, 56,
	-27,
}

var yyDef = [...]int16{
	0, -2, 1, 3, 4, 5, 6, 7, 8, 9,
	10, 11, 0, 0, 0, 0, 0, 0, 0, 0,
	43, 44, 45, 46, 48, 50, 57, 58, 59, 2,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 47, 49, 51, 52, 54, 55, 20,
	0, 0, 0, 0, 25, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 173, 174, 0, 0, 0, 0, 53, 56,
	0, 0, 0, 150, 0, 121, 108, 109, 126, 122,
	128, 141, 145, 0, 151, 152, 153, 154, 0, 0,
	0, 0, 0, 0, 62, -2, 66, 0, 0, 0,
	80, 79, 0, 27, 0, 0, 0, 31, 0, 0,
	190, 0, 0, 0, 34, 0, 0, 0, 0, 39,
	0, 0, 12, 0, 0, 0, 0, 0, 0, 0,
	0, 176, 0, 0, 0, 0, 0, 0, 24, 0,
	0, 0, 114, 115, 0, 0, 0, 0, 0, 159,
	150, 0, 0, 0, 134, 135, 136, 137, 138, 139,
	129, 130, 131, 132, 133, 0, 166, 0, 142, 143,
	0, 146, 147, 148, 0, 155, 156, 157, 158, 122,
	0, 0, 0, 67, 0, 0, 0, 0, 0, 29,
	0, 0, 32, 0, 0, 189, 0, 0, 0, 0,
	35, 0, 37, 0, 0, 0, 0, 0, 0, 62,
	0, 15, 0, 0, 171, 172, 175, 177, 0, 178,
	0, 0, 22, 23, 110, 111, 112, 116, 117, 118,
	119, 120, 0, 159, 125, 127, 0, 0, 165, 168,
	140, 144, 149, 0, 0, 0, 0, 60, 78, 65,
	64, 0, 71, 0, 0, 0, 0, 28, 0, 182,
	0, 169, 191, 0, 0, 0, 0, 0, 0, 0,
	170, 0, 42, 40, 0, 13, 0, 0, 0, 16,
	17, 0, 179, 0, 113, 124, 164, 0, 160, 0,
	0, 163, 82, 0, 0, 69, 0, 72, 73, 74,
	26, 30, 0, 181, 184, 185, 33, 0, 0, 194,
	0, 0, 197, 198, 0, 38, 41, 18, 65, 14,
	182, 0, 0, 167, 161, 162, 0, 76, 77, 0,
	0, 0, 61, 0, 70, 0, 0, 186, 187, 192,
	193, 0, 196, 199, 0, 0, 21, 0, 75, 81,
	83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
	122, 0, 95, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 36, 183, 188, 0, 19,
	0, 123, 0, 94, 0, 0, 105, 0, 106, 0,
	102, 103, 0, 0, 195, 180, 93, 0, 0, 0,
	104, 0, 107, 101, 68, 0, 0, 105, 0, 96,
	98, 0, 0, 0, 105, 0, 97, 0, 100, 0,
	99,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 72, 3, 3, 3, 71, 63, 3,
	55, 56, 54, 68, 57, 69, 62, 70, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 61, 51,
	66, 58, 67, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 52, 3, 53, 65, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 59, 64, 60, 73,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:57
		{
			yylex.(*lexer).result = &Node{Kind: KindProgram, Children: yyDollar[1].nodes}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:62
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].nodes...)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:64
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:68
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:69
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:70
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:71
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:72
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:73
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:74
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:75
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:80
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: yyDollar[2].typ, Name: yyDollar[3].sval, IsExtern: true}}
		}
	case 13:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:82
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[3].sval, IsExtern: true, ElemType: yyDollar[2].typ}}
		}
	case 14:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:84
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[4].sval, IsExtern: true, ElemType: ptrType(yyDollar[2].typ)}}
		}
	case 15:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:86
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: ptrType(yyDollar[2].typ), Name: yyDollar[4].sval, IsExtern: true}}
		}
	case 16:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:88
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: ptrPtrType(ptrType(yyDollar[2].typ)), Name: yyDollar[5].sval, IsExtern: true}}
		}
	case 17:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:90
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeIntPtr, Name: yyDollar[5].sval, IsExtern: true, StructTag: yyDollar[3].sval}}
		}
	case 18:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:92
		{
			n := &Node{Kind: KindFunDecl, Type: yyDollar[2].typ, Name: yyDollar[3].sval, IsExtern: true}
			n.Children = yyDollar[5].nodes
			yyVAL.nodes = []*Node{n}
		}
	case 19:
		yyDollar = yyS[yypt-9 : yypt+1]
//line cmd/gaston/grammar.y:98
		{
			n := &Node{Kind: KindFunDecl, Type: yyDollar[2].typ, Name: yyDollar[3].sval, IsExtern: true}
			n.Children = append(yyDollar[5].nodes, &Node{Kind: KindParam, Type: TypeVoid, Name: "..."})
			yyVAL.nodes = []*Node{n}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:107
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval}}
		}
	case 21:
		yyDollar = yyS[yypt-9 : yypt+1]
//line cmd/gaston/grammar.y:109
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[2].sval, Val: yyDollar[4].ival, Dim2: yyDollar[7].ival, ElemType: yyDollar[1].typ}}
		}
	case 22:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:111
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[2].sval, Val: yyDollar[4].ival, ElemType: yyDollar[1].typ}}
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:113
		{
			n := &Node{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[2].sval, IsVLA: true, ElemType: yyDollar[1].typ}
			n.Children = []*Node{{Kind: KindVar, Name: yyDollar[4].sval}}
			yyVAL.nodes = []*Node{n}
		}
	case 24:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:119
		{
			n := &Node{Kind: KindVarDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
			n.Children = []*Node{yyDollar[4].node}
			yyVAL.nodes = []*Node{n}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:121
		{
			yyVAL.nodes = makeMultiDecl(yyDollar[1].typ, yyDollar[2].nodes)
		}
	case 26:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:123
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[3].sval, Val: yyDollar[5].ival, ElemType: ptrType(yyDollar[1].typ)}}
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:125
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: ptrType(yyDollar[1].typ), Name: yyDollar[3].sval}}
		}
	case 28:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:127
		{
			n := &Node{Kind: KindVarDecl, Type: ptrType(yyDollar[1].typ), Name: yyDollar[3].sval}
			n.Children = []*Node{yyDollar[5].node}
			yyVAL.nodes = []*Node{n}
		}
	case 29:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:129
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: ptrPtrType(ptrType(yyDollar[1].typ)), Name: yyDollar[4].sval}}
		}
	case 30:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:131
		{
			n := &Node{Kind: KindVarDecl, Type: ptrPtrType(ptrType(yyDollar[1].typ)), Name: yyDollar[4].sval}
			n.Children = []*Node{yyDollar[6].node}
			yyVAL.nodes = []*Node{n}
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:133
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeStruct, Name: yyDollar[3].sval, StructTag: yyDollar[2].sval}}
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:135
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeIntPtr, Name: yyDollar[4].sval, StructTag: yyDollar[2].sval}}
		}
	case 33:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:137
		{
			n := &Node{Kind: KindVarDecl, Type: TypeIntPtr, Name: yyDollar[4].sval, StructTag: yyDollar[2].sval}
			n.Children = []*Node{yyDollar[6].node}
			yyVAL.nodes = []*Node{n}
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:139
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeStruct, Name: yyDollar[3].sval, StructTag: yyDollar[2].sval}}
		}
	case 35:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:141
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeIntPtr, Name: yyDollar[4].sval, StructTag: yyDollar[2].sval}}
		}
	case 36:
		yyDollar = yyS[yypt-9 : yypt+1]
//line cmd/gaston/grammar.y:143
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeFuncPtr, Name: yyDollar[4].sval}}
		}
	case 37:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:145
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: ptrType(yyDollar[2].typ), Name: yyDollar[4].sval, IsConstTarget: true}}
		}
	case 38:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:147
		{
			n := &Node{Kind: KindVarDecl, Type: ptrType(yyDollar[2].typ), Name: yyDollar[4].sval, IsConstTarget: true}
			n.Children = []*Node{yyDollar[6].node}
			yyVAL.nodes = []*Node{n}
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:149
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: yyDollar[2].typ, Name: yyDollar[3].sval, IsStatic: true}}
		}
	case 40:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:151
		{
			n := &Node{Kind: KindVarDecl, Type: yyDollar[2].typ, Name: yyDollar[3].sval, IsStatic: true}
			n.Children = []*Node{yyDollar[5].node}
			yyVAL.nodes = []*Node{n}
		}
	case 41:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:153
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[3].sval, Val: yyDollar[5].ival, ElemType: yyDollar[2].typ, IsStatic: true}}
		}
	case 42:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:158
		{
			yyVAL.nodes = []*Node{{Kind: KindVarDecl, Type: yyDollar[2].typ, Name: yyDollar[3].sval, Val: yyDollar[5].ival, IsConst: true}}
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:162
		{
			yyVAL.typ = TypeInt
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:163
		{
			yyVAL.typ = TypeVoid
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:164
		{
			yyVAL.typ = TypeChar
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:165
		{
			yyVAL.typ = TypeInt
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:166
		{
			yyVAL.typ = TypeInt
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:167
		{
			yyVAL.typ = TypeShort
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:168
		{
			yyVAL.typ = TypeShort
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:169
		{
			yyVAL.typ = TypeUnsignedInt
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:170
		{
			yyVAL.typ = TypeUnsignedInt
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:171
		{
			yyVAL.typ = TypeUnsignedInt
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:172
		{
			yyVAL.typ = TypeUnsignedInt
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:173
		{
			yyVAL.typ = TypeUnsignedChar
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:174
		{
			yyVAL.typ = TypeUnsignedShort
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:175
		{
			yyVAL.typ = TypeUnsignedShort
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:176
		{
			yyVAL.typ = TypeFloat
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:177
		{
			yyVAL.typ = TypeDouble
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:178
		{
			yyVAL.typ = yylex.(*lexer).lookupTypedefKind(yyDollar[1].sval)
		}
	case 60:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:183
		{
			n := &Node{Kind: KindFunDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
			n.Children = append(yyDollar[4].nodes, yyDollar[6].node)
			yyVAL.node = n
		}
	case 61:
		yyDollar = yyS[yypt-8 : yypt+1]
//line cmd/gaston/grammar.y:189
		{
			n := &Node{Kind: KindFunDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
			params := append(yyDollar[4].nodes, &Node{Kind: KindParam, Type: TypeVoid, Name: "..."})
			n.Children = append(params, yyDollar[8].node)
			yyVAL.node = n
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:198
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:199
		{
			yyVAL.nodes = nil
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:204
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:206
		{
			yyVAL.nodes = append(yyDollar[1].nodes, &Node{Kind: KindParam, Type: TypeVoid, Name: "..."})
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:208
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:213
		{
			yyVAL.node = &Node{Kind: KindParam, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
		}
	case 68:
		yyDollar = yyS[yypt-8 : yypt+1]
//line cmd/gaston/grammar.y:215
		{
			yyVAL.node = &Node{Kind: KindParam, Type: TypeIntArray, Name: yyDollar[2].sval, ElemType: yyDollar[1].typ, Dim2: yyDollar[7].ival}
		}
	case 69:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:217
		{
			yyVAL.node = &Node{Kind: KindParam, Type: TypeIntArray, Name: yyDollar[2].sval, ElemType: yyDollar[1].typ}
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:219
		{
			yyVAL.node = &Node{Kind: KindParam, Type: TypeIntArray, Name: yyDollar[3].sval, ElemType: ptrType(yyDollar[1].typ)}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:221
		{
			yyVAL.node = &Node{Kind: KindParam, Type: ptrType(yyDollar[1].typ), Name: yyDollar[3].sval}
		}
	case 72:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:223
		{
			yyVAL.node = &Node{Kind: KindParam, Type: ptrPtrType(ptrType(yyDollar[1].typ)), Name: yyDollar[4].sval}
		}
	case 73:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:225
		{
			yyVAL.node = &Node{Kind: KindParam, Type: TypeIntPtr, Name: yyDollar[4].sval, StructTag: yyDollar[2].sval}
		}
	case 74:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:227
		{
			yyVAL.node = &Node{Kind: KindParam, Type: ptrType(yyDollar[2].typ), Name: yyDollar[4].sval, IsConstTarget: true}
		}
	case 75:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:232
		{
			yyVAL.node = &Node{Kind: KindCompound, Children: append(yyDollar[2].nodes, yyDollar[3].nodes...)}
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:237
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].nodes...)
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:239
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].nodes...)
		}
	case 78:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:241
		{
			yyVAL.nodes = nil
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:246
		{
			yyVAL.nodes = append(yyDollar[1].nodes, &Node{Kind: KindVar, Name: yyDollar[3].sval})
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:248
		{
			yyVAL.nodes = []*Node{{Kind: KindVar, Name: yyDollar[1].sval}, {Kind: KindVar, Name: yyDollar[3].sval}}
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:253
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 82:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:255
		{
			yyVAL.nodes = nil
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:259
		{
			yyVAL.node = yyDollar[1].node
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:260
		{
			yyVAL.node = yyDollar[1].node
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:261
		{
			yyVAL.node = yyDollar[1].node
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:262
		{
			yyVAL.node = yyDollar[1].node
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:263
		{
			yyVAL.node = yyDollar[1].node
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:264
		{
			yyVAL.node = yyDollar[1].node
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:265
		{
			yyVAL.node = yyDollar[1].node
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:266
		{
			yyVAL.node = yyDollar[1].node
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:267
		{
			yyVAL.node = yyDollar[1].node
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:268
		{
			yyVAL.node = yyDollar[1].node
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:270
		{
			yyVAL.node = &Node{Kind: KindLabel, Name: yyDollar[1].sval, Children: []*Node{yyDollar[3].node}}
		}
	case 94:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:274
		{
			yyVAL.node = &Node{Kind: KindExprStmt, Children: []*Node{yyDollar[1].node}}
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:275
		{
			yyVAL.node = &Node{Kind: KindExprStmt}
		}
	case 96:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:280
		{
			yyVAL.node = &Node{Kind: KindSelection, Children: []*Node{yyDollar[3].node, yyDollar[5].node}}
		}
	case 97:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:282
		{
			yyVAL.node = &Node{Kind: KindSelection, Children: []*Node{yyDollar[3].node, yyDollar[5].node, yyDollar[7].node}}
		}
	case 98:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:287
		{
			yyVAL.node = &Node{Kind: KindIteration, Children: []*Node{yyDollar[3].node, yyDollar[5].node}}
		}
	case 99:
		yyDollar = yyS[yypt-9 : yypt+1]
//line cmd/gaston/grammar.y:292
		{
			yyVAL.node = &Node{Kind: KindFor, Children: []*Node{yyDollar[3].node, yyDollar[5].node, yyDollar[7].node, yyDollar[9].node}}
		}
	case 100:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:297
		{
			yyVAL.node = &Node{Kind: KindDoWhile, Children: []*Node{yyDollar[2].node, yyDollar[5].node}}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:302
		{
			yyVAL.node = &Node{Kind: KindGoto, Name: yyDollar[2].sval}
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:307
		{
			yyVAL.node = &Node{Kind: KindBreak}
		}
	case 103:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:312
		{
			yyVAL.node = &Node{Kind: KindContinue}
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:316
		{
			yyVAL.node = yyDollar[1].node
		}
	case 105:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:317
		{
			yyVAL.node = nil
		}
	case 106:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:322
		{
			yyVAL.node = &Node{Kind: KindReturn}
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:324
		{
			yyVAL.node = &Node{Kind: KindReturn, Children: []*Node{yyDollar[2].node}}
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:329
		{
			yyVAL.node = yyDollar[1].node
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:331
		{
			yyVAL.node = yyDollar[1].node
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:333
		{
			yyVAL.node = &Node{Kind: KindFieldAccess, Op: "->", Name: yyDollar[3].sval, Children: []*Node{yyDollar[1].node}}
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:335
		{
			yyVAL.node = &Node{Kind: KindFieldAccess, Op: ".", Name: yyDollar[3].sval, Children: []*Node{yyDollar[1].node}}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:340
		{
			yyVAL.node = &Node{Kind: KindAssign, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 113:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:342
		{
			lhs := &Node{Kind: KindDeref, Children: []*Node{yyDollar[2].node}}
			yyVAL.node = &Node{Kind: KindAssign, Children: []*Node{lhs, yyDollar[4].node}}
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:344
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "+", Val: 1, Children: []*Node{yyDollar[1].node, nil}}
		}
	case 115:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:346
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "-", Val: 1, Children: []*Node{yyDollar[1].node, nil}}
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:348
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "+", Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:350
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "-", Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:352
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "*", Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:354
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "/", Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:356
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "%", Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:358
		{
			yyVAL.node = yyDollar[1].node
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:363
		{
			yyVAL.node = &Node{Kind: KindVar, Name: yyDollar[1].sval}
		}
	case 123:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:365
		{
			yyVAL.node = &Node{Kind: KindArray2D, Name: yyDollar[1].sval, Children: []*Node{yyDollar[3].node, yyDollar[6].node}}
		}
	case 124:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:367
		{
			yyVAL.node = &Node{Kind: KindArrayVar, Name: yyDollar[1].sval, Children: []*Node{yyDollar[3].node}}
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:372
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:374
		{
			yyVAL.node = yyDollar[1].node
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:379
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:381
		{
			yyVAL.node = yyDollar[1].node
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:385
		{
			yyVAL.sval = "&"
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:386
		{
			yyVAL.sval = "|"
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:387
		{
			yyVAL.sval = "^"
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:388
		{
			yyVAL.sval = "<<"
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:389
		{
			yyVAL.sval = ">>"
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:393
		{
			yyVAL.sval = "<="
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:394
		{
			yyVAL.sval = "<"
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:395
		{
			yyVAL.sval = ">"
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:396
		{
			yyVAL.sval = ">="
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:397
		{
			yyVAL.sval = "=="
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:398
		{
			yyVAL.sval = "!="
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:403
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:405
		{
			yyVAL.node = yyDollar[1].node
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:409
		{
			yyVAL.sval = "+"
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:410
		{
			yyVAL.sval = "-"
		}
	case 144:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:415
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:417
		{
			yyVAL.node = yyDollar[1].node
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:421
		{
			yyVAL.sval = "*"
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:422
		{
			yyVAL.sval = "/"
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:423
		{
			yyVAL.sval = "%"
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:427
		{
			yyVAL.node = yyDollar[2].node
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:428
		{
			yyVAL.node = yyDollar[1].node
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:429
		{
			yyVAL.node = &Node{Kind: KindNum, Val: yyDollar[1].ival}
		}
	case 152:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:430
		{
			yyVAL.node = &Node{Kind: KindFNum, FVal: yyDollar[1].fval, Type: TypeDouble}
		}
	case 153:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:431
		{
			yyVAL.node = &Node{Kind: KindCharLit, Val: yyDollar[1].ival, Type: TypeInt}
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:432
		{
			yyVAL.node = &Node{Kind: KindStrLit, Name: yyDollar[1].sval, Type: TypeCharPtr}
		}
	case 155:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:433
		{
			yyVAL.node = &Node{Kind: KindUnary, Op: "-", Children: []*Node{yyDollar[2].node}}
		}
	case 156:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:434
		{
			yyVAL.node = &Node{Kind: KindUnary, Op: "!", Children: []*Node{yyDollar[2].node}}
		}
	case 157:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:435
		{
			yyVAL.node = &Node{Kind: KindUnary, Op: "~", Children: []*Node{yyDollar[2].node}}
		}
	case 158:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:436
		{
			yyVAL.node = &Node{Kind: KindAddrOf, Children: []*Node{yyDollar[2].node}}
		}
	case 159:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:437
		{
			yyVAL.node = &Node{Kind: KindDeref, Children: []*Node{yyDollar[2].node}}
		}
	case 160:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:439
		{
			yyVAL.node = &Node{Kind: KindSizeof, Type: yyDollar[3].typ}
		}
	case 161:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:441
		{
			yyVAL.node = &Node{Kind: KindSizeof, StructTag: yyDollar[4].sval}
		}
	case 162:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:443
		{
			yyVAL.node = &Node{Kind: KindSizeof, StructTag: yyDollar[4].sval}
		}
	case 163:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:445
		{
			yyVAL.node = &Node{Kind: KindSizeof, Children: []*Node{yyDollar[3].node}}
		}
	case 164:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:450
		{
			yyVAL.node = &Node{Kind: KindCall, Name: yyDollar[1].sval, Children: yyDollar[3].nodes}
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:454
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 166:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:455
		{
			yyVAL.nodes = nil
		}
	case 167:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:460
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:462
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	case 169:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:467
		{
			yyVAL.nodes = []*Node{{Kind: KindStructDef, Name: yyDollar[2].sval, Children: yyDollar[4].nodes}}
		}
	case 170:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:472
		{
			yyVAL.nodes = []*Node{{Kind: KindStructDef, Name: yyDollar[2].sval, Children: yyDollar[4].nodes, IsUnion: true}}
		}
	case 171:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:477
		{
			yyVAL.nodes = yyDollar[3].nodes
		}
	case 172:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:482
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 173:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:484
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:489
		{
			n := &Node{Kind: KindVarDecl, Type: TypeInt, Name: yyDollar[1].sval,
				Val: yylex.(*lexer).enumAutoVal, IsConst: true}
			yylex.(*lexer).enumAutoVal++
			yyVAL.node = n
		}
	case 175:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:496
		{
			yylex.(*lexer).enumAutoVal = yyDollar[3].ival + 1
			yyVAL.node = &Node{Kind: KindVarDecl, Type: TypeInt, Name: yyDollar[1].sval, Val: yyDollar[3].ival, IsConst: true}
		}
	case 176:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:504
		{
			yylex.(*lexer).registerTypedef(yyDollar[3].sval, yyDollar[2].typ, "")
			yyVAL.nodes = nil
		}
	case 177:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:509
		{
			yylex.(*lexer).registerTypedef(yyDollar[4].sval, ptrType(yyDollar[2].typ), "")
			yyVAL.nodes = nil
		}
	case 178:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:514
		{
			yylex.(*lexer).registerTypedef(yyDollar[4].sval, TypeStruct, yyDollar[3].sval)
			yyVAL.nodes = nil
		}
	case 179:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:519
		{
			yylex.(*lexer).registerTypedef(yyDollar[5].sval, TypeIntPtr, yyDollar[3].sval)
			yyVAL.nodes = nil
		}
	case 180:
		yyDollar = yyS[yypt-10 : yypt+1]
//line cmd/gaston/grammar.y:524
		{
			yylex.(*lexer).registerTypedef(yyDollar[5].sval, TypeFuncPtr, "")
			yyVAL.nodes = nil
		}
	case 181:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:531
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 182:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:532
		{
			yyVAL.nodes = nil
		}
	case 183:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:537
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:539
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:543
		{
			yyVAL.node = &Node{Kind: KindParam, Type: yyDollar[1].typ}
		}
	case 186:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:544
		{
			yyVAL.node = &Node{Kind: KindParam, Type: ptrType(yyDollar[1].typ)}
		}
	case 187:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:545
		{
			yyVAL.node = &Node{Kind: KindParam, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
		}
	case 188:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:546
		{
			yyVAL.node = &Node{Kind: KindParam, Type: ptrType(yyDollar[1].typ), Name: yyDollar[3].sval}
		}
	case 189:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:551
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:553
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	case 191:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:558
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
		}
	case 192:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:560
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval, BitWidth: yyDollar[4].ival}
		}
	case 193:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:562
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[2].sval, Val: -1, ElemType: yyDollar[1].typ}
		}
	case 194:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:564
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: ptrType(yyDollar[1].typ), Name: yyDollar[3].sval}
		}
	case 195:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:566
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[3].sval, Val: yyDollar[5].ival, ElemType: ptrType(yyDollar[1].typ)}
		}
	case 196:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:568
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: TypeIntPtr, Name: yyDollar[4].sval, StructTag: yyDollar[2].sval}
		}
	case 197:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:570
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: TypeStruct, Name: yyDollar[3].sval, StructTag: yyDollar[2].sval}
		}
	case 198:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:572
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: TypeStruct, Name: yyDollar[3].sval, StructTag: yyDollar[2].sval}
		}
	case 199:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:574
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: TypeIntPtr, Name: yyDollar[4].sval, StructTag: yyDollar[2].sval}
		}
	}
	goto yystack /* stack new state and value */
}
