// Code generated by goyacc -v /dev/null -o cmd/gaston/parser.go cmd/gaston/grammar.y. DO NOT EDIT.

//line cmd/gaston/grammar.y:7
package main

import __yyfmt__ "fmt"

//line cmd/gaston/grammar.y:7

//line cmd/gaston/grammar.y:10
type yySymType struct {
	yys   int
	ival  int
	sval  string
	node  *Node
	nodes []*Node
	typ   TypeKind
}

const NUM = 57346
const ID = 57347
const INT = 57348
const VOID = 57349
const IF = 57350
const ELSE = 57351
const WHILE = 57352
const RETURN = 57353
const FOR = 57354
const DO = 57355
const BREAK = 57356
const CONTINUE = 57357
const LE = 57358
const GE = 57359
const EQ = 57360
const NE = 57361
const LSHIFT = 57362
const RSHIFT = 57363
const INC = 57364
const DEC = 57365
const PLUSEQ = 57366
const MINUSEQ = 57367
const STAREQ = 57368
const DIVEQ = 57369
const MODEQ = 57370
const LOWER_THAN_ELSE = 57371

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUM",
	"ID",
	"INT",
	"VOID",
	"IF",
	"ELSE",
	"WHILE",
	"RETURN",
	"FOR",
	"DO",
	"BREAK",
	"CONTINUE",
	"LE",
	"GE",
	"EQ",
	"NE",
	"LSHIFT",
	"RSHIFT",
	"INC",
	"DEC",
	"PLUSEQ",
	"MINUSEQ",
	"STAREQ",
	"DIVEQ",
	"MODEQ",
	"LOWER_THAN_ELSE",
	"';'",
	"'['",
	"']'",
	"'='",
	"'('",
	"')'",
	"','",
	"'{'",
	"'}'",
	"'&'",
	"'|'",
	"'^'",
	"'<'",
	"'>'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'!'",
	"'~'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line cmd/gaston/grammar.y:297

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 215

var yyAct = [...]uint8{
	115, 6, 4, 33, 105, 136, 107, 17, 22, 64,
	65, 66, 21, 92, 16, 20, 61, 62, 97, 73,
	23, 26, 19, 11, 12, 67, 13, 14, 153, 154,
	150, 141, 140, 58, 59, 69, 69, 69, 76, 96,
	90, 77, 78, 79, 80, 81, 82, 85, 68, 70,
	71, 24, 55, 56, 57, 69, 69, 11, 12, 72,
	13, 87, 27, 86, 143, 128, 28, 29, 69, 88,
	45, 69, 127, 46, 126, 99, 95, 93, 35, 91,
	94, 149, 142, 139, 89, 26, 19, 133, 132, 117,
	125, 118, 121, 119, 120, 122, 123, 75, 100, 36,
	103, 102, 138, 148, 7, 8, 26, 19, 15, 34,
	32, 116, 34, 124, 74, 24, 10, 3, 92, 104,
	9, 48, 131, 63, 60, 129, 27, 134, 135, 137,
	28, 29, 130, 47, 84, 83, 24, 25, 18, 114,
	113, 112, 111, 137, 147, 144, 145, 27, 146, 110,
	137, 28, 29, 151, 109, 152, 26, 19, 108, 155,
	117, 106, 118, 121, 119, 120, 122, 123, 101, 49,
	52, 53, 54, 58, 59, 98, 31, 30, 2, 5,
	1, 0, 116, 0, 0, 0, 24, 0, 0, 92,
	0, 0, 55, 56, 57, 50, 51, 27, 0, 0,
	0, 28, 29, 38, 39, 40, 41, 42, 43, 44,
	0, 0, 0, 0, 37,
}

var yyPact = [...]int16{
	98, -1000, 98, -1000, -1000, -1000, 111, -1000, -1000, -1000,
	-7, -1000, 104, 17, 103, 46, 69, 181, -1000, 39,
	153, -28, -37, -1000, 17, -1000, -1000, 17, 17, 17,
	24, -17, -1000, -1000, 109, 67, -1000, 17, -1000, -1000,
	17, 17, 17, 17, 17, 17, 17, 17, 17, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	17, -1000, -1000, 17, -1000, -1000, -1000, 5, -1000, -1000,
	-1000, -1000, -24, 106, 49, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 44, 4, -18, -1000, 13, -28, -37, -1000,
	-1000, -1000, -1000, -1000, 43, -1000, -1000, 17, 98, -1000,
	-1000, 81, -1000, 108, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 60, -1000, 40, 38, 31,
	152, 102, 58, 57, 27, -1000, 17, 17, 17, 92,
	-1000, 53, -1000, -1000, -3, -4, 52, -1000, 30, -1000,
	152, 152, 17, 17, 94, -1000, 51, -5, 152, 17,
	-2, -1000, -6, -1000, 152, -1000,
}

var yyPgo = [...]uint8{
	0, 180, 117, 2, 179, 178, 177, 176, 3, 6,
	175, 168, 4, 161, 158, 154, 149, 142, 141, 140,
	139, 5, 0, 7, 138, 15, 12, 8, 20, 137,
	135, 134, 1, 133, 124, 123, 121,
}

var yyR1 = [...]int8{
	0, 1, 5, 5, 2, 2, 3, 3, 3, 32,
	32, 4, 6, 6, 7, 7, 8, 8, 9, 10,
	10, 11, 11, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 13, 13, 14, 14, 15, 16, 17, 19,
	20, 21, 21, 18, 18, 22, 22, 22, 22, 22,
	22, 22, 22, 22, 23, 23, 24, 24, 25, 25,
	36, 36, 36, 36, 36, 33, 33, 33, 33, 33,
	33, 26, 26, 34, 34, 27, 27, 35, 35, 35,
	28, 28, 28, 28, 28, 28, 28, 29, 30, 30,
	31, 31,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 1, 1, 3, 6, 5, 1,
	1, 6, 1, 1, 3, 1, 2, 4, 4, 2,
	0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 1, 5, 7, 5, 9, 7, 2,
	2, 1, 0, 2, 3, 3, 2, 2, 3, 3,
	3, 3, 3, 1, 1, 4, 3, 1, 3, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 3, 1, 1, 1, 3, 1, 1, 1, 1,
	3, 1, 1, 1, 2, 2, 2, 4, 1, 0,
	3, 1,
}

var yyChk = [...]int16{
	-1000, -1, -5, -2, -3, -4, -32, 6, 7, -2,
	5, 30, 31, 33, 34, 4, -22, -23, -24, 5,
	-25, -26, -27, -28, 34, -29, 4, 45, 49, 50,
	-6, -7, 7, -8, 6, 32, 30, 33, 22, 23,
	24, 25, 26, 27, 28, 31, 34, -33, -36, 16,
	42, 43, 17, 18, 19, 39, 40, 41, 20, 21,
	-34, 44, 45, -35, 46, 47, 48, -22, -28, -23,
	-28, -28, 35, 36, 5, 30, -22, -22, -22, -22,
	-22, -22, -22, -30, -31, -22, -25, -26, -27, -28,
	35, -9, 37, -8, 31, 32, 35, 36, -10, 32,
	-22, -11, -3, -32, 38, -12, -13, -9, -14, -15,
	-16, -17, -18, -19, -20, -22, 30, 8, 10, 12,
	13, 11, 14, 15, 5, 30, 34, 34, 34, -12,
	30, -22, 30, 30, -22, -22, -21, -22, 10, 30,
	35, 35, 30, 34, -12, -12, -21, -22, 9, 30,
	35, -12, -21, 30, 35, -12,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 4, 5, 0, 9, 10, 2,
	0, 6, 0, 0, 0, 0, 0, 81, 53, 54,
	57, 59, 72, 76, 0, 82, 83, 0, 0, 0,
	0, 12, 13, 15, 0, 0, 8, 0, 46, 47,
	0, 0, 0, 0, 0, 0, 89, 0, 0, 65,
	66, 67, 68, 69, 70, 60, 61, 62, 63, 64,
	0, 73, 74, 0, 77, 78, 79, 0, 84, 81,
	85, 86, 0, 0, 16, 7, 45, 48, 49, 50,
	51, 52, 0, 0, 88, 91, 56, 58, 71, 75,
	80, 11, 20, 14, 0, 55, 87, 0, 22, 17,
	90, 0, 19, 0, 18, 21, 23, 24, 25, 26,
	27, 28, 29, 30, 31, 0, 33, 0, 0, 0,
	0, 0, 0, 0, 0, 32, 0, 0, 42, 0,
	43, 0, 39, 40, 0, 0, 0, 41, 0, 44,
	0, 0, 42, 0, 34, 36, 0, 0, 0, 42,
	0, 35, 0, 38, 0, 37,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 49, 3, 3, 3, 48, 39, 3,
	34, 35, 46, 44, 36, 45, 3, 47, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 30,
	42, 33, 43, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 31, 3, 32, 41, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 37, 40, 38, 50,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:49
		{
			yylex.(*lexer).result = &Node{Kind: KindProgram, Children: yyDollar[1].nodes}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:54
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:56
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:60
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:61
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:66
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
		}
	case 7:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:68
		{
			yyVAL.node = &Node{Kind: KindVarDecl, Type: TypeIntArray, Name: yyDollar[2].sval, Val: yyDollar[4].ival}
		}
	case 8:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:70
		{
			n := &Node{Kind: KindVarDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
			n.Children = []*Node{yyDollar[4].node}
			yyVAL.node = n
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:74
		{
			yyVAL.typ = TypeInt
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:75
		{
			yyVAL.typ = TypeVoid
		}
	case 11:
		yyDollar = yyS[yypt-6 : yypt+1]
//line cmd/gaston/grammar.y:80
		{
			n := &Node{Kind: KindFunDecl, Type: yyDollar[1].typ, Name: yyDollar[2].sval}
			n.Children = append(yyDollar[4].nodes, yyDollar[6].node)
			yyVAL.node = n
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:88
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:89
		{
			yyVAL.nodes = nil
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:94
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:96
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:101
		{
			yyVAL.node = &Node{Kind: KindParam, Type: TypeInt, Name: yyDollar[2].sval}
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:103
		{
			yyVAL.node = &Node{Kind: KindParam, Type: TypeIntArray, Name: yyDollar[2].sval}
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:108
		{
			yyVAL.node = &Node{Kind: KindCompound, Children: append(yyDollar[2].nodes, yyDollar[3].nodes...)}
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:113
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:115
		{
			yyVAL.nodes = nil
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:120
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 22:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:122
		{
			yyVAL.nodes = nil
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:126
		{
			yyVAL.node = yyDollar[1].node
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:127
		{
			yyVAL.node = yyDollar[1].node
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:128
		{
			yyVAL.node = yyDollar[1].node
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:129
		{
			yyVAL.node = yyDollar[1].node
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:130
		{
			yyVAL.node = yyDollar[1].node
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:131
		{
			yyVAL.node = yyDollar[1].node
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:132
		{
			yyVAL.node = yyDollar[1].node
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:133
		{
			yyVAL.node = yyDollar[1].node
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:134
		{
			yyVAL.node = yyDollar[1].node
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:138
		{
			yyVAL.node = &Node{Kind: KindExprStmt, Children: []*Node{yyDollar[1].node}}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:139
		{
			yyVAL.node = &Node{Kind: KindExprStmt}
		}
	case 34:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:144
		{
			yyVAL.node = &Node{Kind: KindSelection, Children: []*Node{yyDollar[3].node, yyDollar[5].node}}
		}
	case 35:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:146
		{
			yyVAL.node = &Node{Kind: KindSelection, Children: []*Node{yyDollar[3].node, yyDollar[5].node, yyDollar[7].node}}
		}
	case 36:
		yyDollar = yyS[yypt-5 : yypt+1]
//line cmd/gaston/grammar.y:151
		{
			yyVAL.node = &Node{Kind: KindIteration, Children: []*Node{yyDollar[3].node, yyDollar[5].node}}
		}
	case 37:
		yyDollar = yyS[yypt-9 : yypt+1]
//line cmd/gaston/grammar.y:156
		{
			yyVAL.node = &Node{Kind: KindFor, Children: []*Node{yyDollar[3].node, yyDollar[5].node, yyDollar[7].node, yyDollar[9].node}}
		}
	case 38:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/gaston/grammar.y:161
		{
			yyVAL.node = &Node{Kind: KindDoWhile, Children: []*Node{yyDollar[2].node, yyDollar[5].node}}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:166
		{
			yyVAL.node = &Node{Kind: KindBreak}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:171
		{
			yyVAL.node = &Node{Kind: KindContinue}
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:175
		{
			yyVAL.node = yyDollar[1].node
		}
	case 42:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:176
		{
			yyVAL.node = nil
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:181
		{
			yyVAL.node = &Node{Kind: KindReturn}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:183
		{
			yyVAL.node = &Node{Kind: KindReturn, Children: []*Node{yyDollar[2].node}}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:188
		{
			yyVAL.node = &Node{Kind: KindAssign, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:190
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "+", Val: 1, Children: []*Node{yyDollar[1].node, nil}}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:192
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "-", Val: 1, Children: []*Node{yyDollar[1].node, nil}}
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:194
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "+", Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:196
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "-", Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:198
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "*", Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:200
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "/", Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:202
		{
			yyVAL.node = &Node{Kind: KindCompoundAssign, Op: "%", Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:204
		{
			yyVAL.node = yyDollar[1].node
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:209
		{
			yyVAL.node = &Node{Kind: KindVar, Name: yyDollar[1].sval}
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:211
		{
			yyVAL.node = &Node{Kind: KindArrayVar, Name: yyDollar[1].sval, Children: []*Node{yyDollar[3].node}}
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:216
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:218
		{
			yyVAL.node = yyDollar[1].node
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:223
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:225
		{
			yyVAL.node = yyDollar[1].node
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:229
		{
			yyVAL.sval = "&"
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:230
		{
			yyVAL.sval = "|"
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:231
		{
			yyVAL.sval = "^"
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:232
		{
			yyVAL.sval = "<<"
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:233
		{
			yyVAL.sval = ">>"
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:237
		{
			yyVAL.sval = "<="
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:238
		{
			yyVAL.sval = "<"
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:239
		{
			yyVAL.sval = ">"
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:240
		{
			yyVAL.sval = ">="
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:241
		{
			yyVAL.sval = "=="
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:242
		{
			yyVAL.sval = "!="
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:247
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:249
		{
			yyVAL.node = yyDollar[1].node
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:253
		{
			yyVAL.sval = "+"
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:254
		{
			yyVAL.sval = "-"
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:259
		{
			yyVAL.node = &Node{Kind: KindBinOp, Op: yyDollar[2].sval, Children: []*Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:261
		{
			yyVAL.node = yyDollar[1].node
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:265
		{
			yyVAL.sval = "*"
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:266
		{
			yyVAL.sval = "/"
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:267
		{
			yyVAL.sval = "%"
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:271
		{
			yyVAL.node = yyDollar[2].node
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:272
		{
			yyVAL.node = yyDollar[1].node
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:273
		{
			yyVAL.node = yyDollar[1].node
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:274
		{
			yyVAL.node = &Node{Kind: KindNum, Val: yyDollar[1].ival}
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:275
		{
			yyVAL.node = &Node{Kind: KindUnary, Op: "-", Children: []*Node{yyDollar[2].node}}
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:276
		{
			yyVAL.node = &Node{Kind: KindUnary, Op: "!", Children: []*Node{yyDollar[2].node}}
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/gaston/grammar.y:277
		{
			yyVAL.node = &Node{Kind: KindUnary, Op: "~", Children: []*Node{yyDollar[2].node}}
		}
	case 87:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/gaston/grammar.y:282
		{
			yyVAL.node = &Node{Kind: KindCall, Name: yyDollar[1].sval, Children: yyDollar[3].nodes}
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:286
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	case 89:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd/gaston/grammar.y:287
		{
			yyVAL.nodes = nil
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/gaston/grammar.y:292
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/gaston/grammar.y:294
		{
			yyVAL.nodes = []*Node{yyDollar[1].node}
		}
	}
	goto yystack /* stack new state and value */
}
