// Code generated by gaston — C-minus → ARM64 Plan 9 assembler
// DO NOT EDIT
//
// Runtime interface (provide these in Go):
//   func gaston_input() int64            // reads one integer from stdin
//   func gaston_output(v int64)           // writes one integer to stdout
//   func gaston_main()                    // call to run the program
#include "textflag.h"

// func gcd(int u, int v)
TEXT gaston_gcd(SB), NOSPLIT, $0
	SUB $80, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29
	MOVD R0, 16(RSP)
	MOVD R1, 24(RSP)

	MOVD 24(RSP), R0
	MOVD $0, R1
	CMP R1, R0
	BEQ gaston_gcd_cmp0
	MOVD $0, R0
	B gaston_gcd_cmp1
gaston_gcd_cmp0:
	MOVD $1, R0
gaston_gcd_cmp1:
	MOVD R0, 32(RSP)
	MOVD 32(RSP), R0
	CMP $0, R0
	BEQ gaston_gcd_L0
	MOVD 16(RSP), R0
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $80, RSP, RSP
	RET
gaston_gcd_L0:
	MOVD 16(RSP), R0
	MOVD 24(RSP), R1
	SDIV R1, R0, R0
	MOVD R0, 40(RSP)
	MOVD 40(RSP), R0
	MOVD 24(RSP), R1
	MUL R1, R0, R0
	MOVD R0, 48(RSP)
	MOVD 16(RSP), R0
	MOVD 48(RSP), R1
	SUB R1, R0, R0
	MOVD R0, 56(RSP)
	MOVD 24(RSP), R0
	MOVD 56(RSP), R1
	CALL gaston_gcd(SB)
	MOVD R0, 64(RSP)
	MOVD 64(RSP), R0
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $80, RSP, RSP
	RET
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $80, RSP, RSP
	RET

// func main(void)
TEXT gaston_main(SB), NOSPLIT, $0
	SUB $64, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	CALL gaston_input(SB)
	MOVD R0, 32(RSP)
	MOVD 32(RSP), R0
	MOVD R0, 16(RSP)
	CALL gaston_input(SB)
	MOVD R0, 40(RSP)
	MOVD 40(RSP), R0
	MOVD R0, 24(RSP)
	MOVD 16(RSP), R0
	MOVD 24(RSP), R1
	CALL gaston_gcd(SB)
	MOVD R0, 48(RSP)
	MOVD 48(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 56(RSP)
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $64, RSP, RSP
	RET

