// Code generated by gaston — C-minus → ARM64 Plan 9 assembler
// DO NOT EDIT
//
// Runtime interface (provide these in Go):
//   func gaston_input() int64            // reads one integer from stdin
//   func gaston_output(v int64)           // writes one integer to stdout
//   func gaston_main()                    // call to run the program
#include "textflag.h"

// func main(void)
TEXT gaston_main(SB), NOSPLIT, $0
	SUB $32, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	MOVD $42, R0
	CALL gaston_output(SB)
	MOVD R0, 16(RSP)
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $32, RSP, RSP
	RET

