// Code generated by gaston — DO NOT EDIT
//
// Build this together with the generated .s file:
//   GOOS=linux GOARCH=arm64 go build -o <progname>
package main

import (
	_ "unsafe" // for go:linkname
	"fmt"
	"os"
)

// gaston_main is defined in the generated .s file.
//
//go:linkname gaston_main gaston_main
func gaston_main()

// gaston_output and gaston_input are called by the generated assembly.
// go:linkname exports them as plain C-style symbols matching the CALL
// instructions in the .s file.

//go:linkname gaston_output gaston_output
func gaston_output(v int64) {
	fmt.Println(v)
}

//go:linkname gaston_input gaston_input
func gaston_input() int64 {
	var v int64
	fmt.Fscan(os.Stdin, &v)
	return v
}

//go:linkname gaston_print_char gaston_print_char
func gaston_print_char(c int64) {
	os.Stdout.Write([]byte{byte(c)})
}

//go:linkname gaston_print_string gaston_print_string
func gaston_print_string(ptr int64) {
	// ptr is a raw address into the process's address space.
	// In the Plan 9 / Go build we can't easily dereference it;
	// this stub exists so the generated .s file links without errors.
	// Real use requires the ELF path where the runtime is inline assembly.
	_ = ptr
}

func main() { gaston_main() }
