// Code generated by gaston — C-minus → ARM64 Plan 9 assembler
// DO NOT EDIT
//
// Runtime interface (provide these in Go):
//   func gaston_input() int64            // reads one integer from stdin
//   func gaston_output(v int64)           // writes one integer to stdout
//   func gaston_main()                    // call to run the program
#include "textflag.h"

// func main(void)
TEXT gaston_main(SB), NOSPLIT, $0
	SUB $272, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	MOVD $0, R0
	MOVD R0, 64(RSP)
gaston_main_L0:
	MOVD 64(RSP), R0
	MOVD $5, R1
	CMP R1, R0
	BLT gaston_main_cmp0
	MOVD $0, R0
	B gaston_main_cmp1
gaston_main_cmp0:
	MOVD $1, R0
gaston_main_cmp1:
	MOVD R0, 72(RSP)
	MOVD 72(RSP), R0
	CMP $0, R0
	BEQ gaston_main_L1
	MOVD 64(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 80(RSP)
	MOVD 80(RSP), R0
	MOVD $10, R1
	MUL R1, R0, R0
	MOVD R0, 88(RSP)
	ADD $16, RSP, R0
	MOVD 64(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD 88(RSP), R2
	MOVD R2, (R0)
	MOVD 64(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 96(RSP)
	MOVD 96(RSP), R0
	MOVD R0, 64(RSP)
	B gaston_main_L0
gaston_main_L1:
	ADD $16, RSP, R0
	MOVD R0, 104(RSP)
	MOVD 104(RSP), R0
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	MOVD (R0), R0
	MOVD R0, 112(RSP)
	MOVD 112(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 120(RSP)
	MOVD $1, R0
	MOVD $8, R1
	MUL R1, R0, R0
	MOVD R0, 128(RSP)
	MOVD 56(RSP), R0
	MOVD R0, 136(RSP)
	MOVD 136(RSP), R0
	MOVD 128(RSP), R1
	ADD R1, R0, R0
	MOVD R0, 144(RSP)
	MOVD 144(RSP), R0
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	MOVD (R0), R0
	MOVD R0, 152(RSP)
	MOVD 152(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 160(RSP)
	MOVD $2, R0
	MOVD $8, R1
	MUL R1, R0, R0
	MOVD R0, 168(RSP)
	MOVD 56(RSP), R0
	MOVD 168(RSP), R1
	ADD R1, R0, R0
	MOVD R0, 176(RSP)
	MOVD 176(RSP), R0
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	MOVD (R0), R0
	MOVD R0, 184(RSP)
	MOVD 184(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 192(RSP)
	MOVD $1, R0
	MOVD $8, R1
	MUL R1, R0, R0
	MOVD R0, 200(RSP)
	MOVD 56(RSP), R0
	MOVD R0, 208(RSP)
	MOVD 208(RSP), R0
	MOVD 200(RSP), R1
	SUB R1, R0, R0
	MOVD R0, 216(RSP)
	MOVD 216(RSP), R0
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	MOVD (R0), R0
	MOVD R0, 224(RSP)
	MOVD 224(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 232(RSP)
	MOVD $2, R0
	MOVD $8, R1
	MUL R1, R0, R0
	MOVD R0, 240(RSP)
	MOVD 56(RSP), R0
	MOVD 240(RSP), R1
	SUB R1, R0, R0
	MOVD R0, 248(RSP)
	MOVD 248(RSP), R0
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	MOVD (R0), R0
	MOVD R0, 256(RSP)
	MOVD 256(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 264(RSP)
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $272, RSP, RSP
	RET

