// Code generated by gaston — C-minus → ARM64 Plan 9 assembler
// DO NOT EDIT
//
// Runtime interface (provide these in Go):
//   func gaston_input() int64            // reads one integer from stdin
//   func gaston_output(v int64)           // writes one integer to stdout
//   func gaston_main()                    // call to run the program
#include "textflag.h"

GLOBL gaston_flags(SB), NOPTR, $808

// func main(void)
TEXT gaston_main(SB), NOSPLIT, $0
	SUB $128, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	MOVD $100, R0
	MOVD R0, 32(RSP)
	MOVD $2, R0
	MOVD R0, 16(RSP)
gaston_main_L0:
	MOVD 16(RSP), R0
	MOVD 32(RSP), R1
	CMP R1, R0
	BLE gaston_main_cmp0
	MOVD $0, R0
	B gaston_main_cmp1
gaston_main_cmp0:
	MOVD $1, R0
gaston_main_cmp1:
	MOVD R0, 40(RSP)
	MOVD 40(RSP), R0
	CMP $0, R0
	BEQ gaston_main_L1
	MOVD $gaston_flags(SB), R0
	MOVD 16(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD $1, R2
	MOVD R2, (R0)
	MOVD 16(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 48(RSP)
	MOVD 48(RSP), R0
	MOVD R0, 16(RSP)
	B gaston_main_L0
gaston_main_L1:
	MOVD $2, R0
	MOVD R0, 16(RSP)
gaston_main_L2:
	MOVD 16(RSP), R0
	MOVD 32(RSP), R1
	CMP R1, R0
	BLE gaston_main_cmp2
	MOVD $0, R0
	B gaston_main_cmp3
gaston_main_cmp2:
	MOVD $1, R0
gaston_main_cmp3:
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	CMP $0, R0
	BEQ gaston_main_L3
	MOVD $gaston_flags(SB), R0
	MOVD 16(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 64(RSP)
	MOVD 64(RSP), R0
	MOVD $1, R1
	CMP R1, R0
	BEQ gaston_main_cmp4
	MOVD $0, R0
	B gaston_main_cmp5
gaston_main_cmp4:
	MOVD $1, R0
gaston_main_cmp5:
	MOVD R0, 72(RSP)
	MOVD 72(RSP), R0
	CMP $0, R0
	BEQ gaston_main_L4
	MOVD 16(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 80(RSP)
	MOVD 16(RSP), R0
	MOVD 16(RSP), R1
	ADD R1, R0, R0
	MOVD R0, 88(RSP)
	MOVD 88(RSP), R0
	MOVD R0, 24(RSP)
gaston_main_L6:
	MOVD 24(RSP), R0
	MOVD 32(RSP), R1
	CMP R1, R0
	BLE gaston_main_cmp6
	MOVD $0, R0
	B gaston_main_cmp7
gaston_main_cmp6:
	MOVD $1, R0
gaston_main_cmp7:
	MOVD R0, 96(RSP)
	MOVD 96(RSP), R0
	CMP $0, R0
	BEQ gaston_main_L7
	MOVD $gaston_flags(SB), R0
	MOVD 24(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD $0, R2
	MOVD R2, (R0)
	MOVD 24(RSP), R0
	MOVD 16(RSP), R1
	ADD R1, R0, R0
	MOVD R0, 104(RSP)
	MOVD 104(RSP), R0
	MOVD R0, 24(RSP)
	B gaston_main_L6
gaston_main_L7:
gaston_main_L4:
	MOVD 16(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 112(RSP)
	MOVD 112(RSP), R0
	MOVD R0, 16(RSP)
	B gaston_main_L2
gaston_main_L3:
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $128, RSP, RSP
	RET

