// Code generated by gaston — C-minus → ARM64 Plan 9 assembler
// DO NOT EDIT
//
// Runtime interface (provide these in Go):
//   func gaston_input() int64            // reads one integer from stdin
//   func gaston_output(v int64)           // writes one integer to stdout
//   func gaston_main()                    // call to run the program
#include "textflag.h"

GLOBL gaston_garr(SB), NOPTR, $24

// func param_size(int a[])
TEXT gaston_param_size(SB), NOSPLIT, $0
	SUB $32, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29
	MOVD R0, 16(RSP)

	MOVD $8, R0
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $32, RSP, RSP
	RET
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $32, RSP, RSP
	RET

// func local_size(void)
TEXT gaston_local_size(SB), NOSPLIT, $0
	SUB $64, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	MOVD $40, R0
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $64, RSP, RSP
	RET
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $64, RSP, RSP
	RET

// func main(void)
TEXT gaston_main(SB), NOSPLIT, $0
	SUB $64, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	MOVD $24, R0
	CALL gaston_output(SB)
	MOVD R0, 16(RSP)
	CALL gaston_local_size(SB)
	MOVD R0, 24(RSP)
	MOVD 24(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 32(RSP)
	MOVD $gaston_garr(SB), R0
	MOVD R0, 40(RSP)
	MOVD 40(RSP), R0
	CALL gaston_param_size(SB)
	MOVD R0, 48(RSP)
	MOVD 48(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 56(RSP)
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $64, RSP, RSP
	RET

