// Code generated by gaston — C-minus → ARM64 Plan 9 assembler
// DO NOT EDIT
//
// Runtime interface (provide these in Go):
//   func gaston_input() int64            // reads one integer from stdin
//   func gaston_output(v int64)           // writes one integer to stdout
//   func gaston_main()                    // call to run the program
#include "textflag.h"

GLOBL gaston_arr(SB), NOPTR, $80

// func minIndex(int a[], int n, int start)
TEXT gaston_minIndex(SB), NOSPLIT, $0
	SUB $112, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29
	MOVD R0, 16(RSP)
	MOVD R1, 24(RSP)
	MOVD R2, 32(RSP)

	MOVD 32(RSP), R0
	MOVD R0, 40(RSP)
	MOVD 32(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	MOVD R0, 48(RSP)
gaston_minIndex_L0:
	MOVD 48(RSP), R0
	MOVD 24(RSP), R1
	CMP R1, R0
	BLT gaston_minIndex_cmp0
	MOVD $0, R0
	B gaston_minIndex_cmp1
gaston_minIndex_cmp0:
	MOVD $1, R0
gaston_minIndex_cmp1:
	MOVD R0, 64(RSP)
	MOVD 64(RSP), R0
	CMP $0, R0
	BEQ gaston_minIndex_L1
	MOVD 16(RSP), R0
	MOVD 48(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 72(RSP)
	MOVD 16(RSP), R0
	MOVD 40(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 80(RSP)
	MOVD 72(RSP), R0
	MOVD 80(RSP), R1
	CMP R1, R0
	BLT gaston_minIndex_cmp2
	MOVD $0, R0
	B gaston_minIndex_cmp3
gaston_minIndex_cmp2:
	MOVD $1, R0
gaston_minIndex_cmp3:
	MOVD R0, 88(RSP)
	MOVD 88(RSP), R0
	CMP $0, R0
	BEQ gaston_minIndex_L2
	MOVD 48(RSP), R0
	MOVD R0, 40(RSP)
gaston_minIndex_L2:
	MOVD 48(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 96(RSP)
	MOVD 96(RSP), R0
	MOVD R0, 48(RSP)
	B gaston_minIndex_L0
gaston_minIndex_L1:
	MOVD 40(RSP), R0
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $112, RSP, RSP
	RET
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $112, RSP, RSP
	RET

// func swap(int a[], int i, int j)
TEXT gaston_swap(SB), NOSPLIT, $0
	SUB $64, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29
	MOVD R0, 16(RSP)
	MOVD R1, 24(RSP)
	MOVD R2, 32(RSP)

	MOVD 16(RSP), R0
	MOVD 24(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 48(RSP)
	MOVD 48(RSP), R0
	MOVD R0, 40(RSP)
	MOVD 16(RSP), R0
	MOVD 32(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 56(RSP)
	MOVD 16(RSP), R0
	MOVD 24(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD 56(RSP), R2
	MOVD R2, (R0)
	MOVD 16(RSP), R0
	MOVD 32(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD 40(RSP), R2
	MOVD R2, (R0)
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $64, RSP, RSP
	RET

// func gcd(int a, int b)
TEXT gaston_gcd(SB), NOSPLIT, $0
	SUB $80, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29
	MOVD R0, 16(RSP)
	MOVD R1, 24(RSP)

gaston_gcd_L0:
	MOVD 24(RSP), R0
	MOVD $0, R1
	CMP R1, R0
	BNE gaston_gcd_cmp0
	MOVD $0, R0
	B gaston_gcd_cmp1
gaston_gcd_cmp0:
	MOVD $1, R0
gaston_gcd_cmp1:
	MOVD R0, 40(RSP)
	MOVD 40(RSP), R0
	CMP $0, R0
	BEQ gaston_gcd_L1
	MOVD 24(RSP), R0
	MOVD R0, 32(RSP)
	MOVD 16(RSP), R0
	MOVD 24(RSP), R1
	SDIV R1, R0, R0
	MOVD R0, 48(RSP)
	MOVD 48(RSP), R0
	MOVD 24(RSP), R1
	MUL R1, R0, R0
	MOVD R0, 56(RSP)
	MOVD 16(RSP), R0
	MOVD 56(RSP), R1
	SUB R1, R0, R0
	MOVD R0, 64(RSP)
	MOVD 64(RSP), R0
	MOVD R0, 24(RSP)
	MOVD 32(RSP), R0
	MOVD R0, 16(RSP)
	B gaston_gcd_L0
gaston_gcd_L1:
	MOVD 16(RSP), R0
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $80, RSP, RSP
	RET
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $80, RSP, RSP
	RET

// func selectionSort(int a[], int n)
TEXT gaston_selectionSort(SB), NOSPLIT, $0
	SUB $112, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29
	MOVD R0, 16(RSP)
	MOVD R1, 24(RSP)

	MOVD $0, R0
	MOVD R0, 32(RSP)
gaston_selectionSort_L0:
	MOVD 24(RSP), R0
	MOVD $1, R1
	SUB R1, R0, R0
	MOVD R0, 48(RSP)
	MOVD 32(RSP), R0
	MOVD 48(RSP), R1
	CMP R1, R0
	BLT gaston_selectionSort_cmp0
	MOVD $0, R0
	B gaston_selectionSort_cmp1
gaston_selectionSort_cmp0:
	MOVD $1, R0
gaston_selectionSort_cmp1:
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	CMP $0, R0
	BEQ gaston_selectionSort_L1
	MOVD 16(RSP), R0
	MOVD R0, 64(RSP)
	MOVD 64(RSP), R0
	MOVD 24(RSP), R1
	MOVD 32(RSP), R2
	CALL gaston_minIndex(SB)
	MOVD R0, 72(RSP)
	MOVD 72(RSP), R0
	MOVD R0, 40(RSP)
	MOVD 40(RSP), R0
	MOVD 32(RSP), R1
	CMP R1, R0
	BNE gaston_selectionSort_cmp2
	MOVD $0, R0
	B gaston_selectionSort_cmp3
gaston_selectionSort_cmp2:
	MOVD $1, R0
gaston_selectionSort_cmp3:
	MOVD R0, 80(RSP)
	MOVD 80(RSP), R0
	CMP $0, R0
	BEQ gaston_selectionSort_L2
	MOVD 16(RSP), R0
	MOVD R0, 88(RSP)
	MOVD 88(RSP), R0
	MOVD 32(RSP), R1
	MOVD 40(RSP), R2
	CALL gaston_swap(SB)
	MOVD R0, 96(RSP)
gaston_selectionSort_L2:
	MOVD 32(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 104(RSP)
	MOVD 104(RSP), R0
	MOVD R0, 32(RSP)
	B gaston_selectionSort_L0
gaston_selectionSort_L1:
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $112, RSP, RSP
	RET

// func main(void)
TEXT gaston_main(SB), NOSPLIT, $0
	SUB $144, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	MOVD $10, R0
	MOVD R0, 24(RSP)
	MOVD $0, R0
	MOVD R0, 16(RSP)
gaston_main_L0:
	MOVD 16(RSP), R0
	MOVD 24(RSP), R1
	CMP R1, R0
	BLT gaston_main_cmp0
	MOVD $0, R0
	B gaston_main_cmp1
gaston_main_cmp0:
	MOVD $1, R0
gaston_main_cmp1:
	MOVD R0, 40(RSP)
	MOVD 40(RSP), R0
	CMP $0, R0
	BEQ gaston_main_L1
	CALL gaston_input(SB)
	MOVD R0, 48(RSP)
	MOVD $gaston_arr(SB), R0
	MOVD 16(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD 48(RSP), R2
	MOVD R2, (R0)
	MOVD 16(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	MOVD R0, 16(RSP)
	B gaston_main_L0
gaston_main_L1:
	MOVD $gaston_arr(SB), R0
	MOVD R0, 64(RSP)
	MOVD 64(RSP), R0
	MOVD 24(RSP), R1
	CALL gaston_selectionSort(SB)
	MOVD R0, 72(RSP)
	MOVD $0, R0
	MOVD R0, 16(RSP)
gaston_main_L2:
	MOVD 16(RSP), R0
	MOVD 24(RSP), R1
	CMP R1, R0
	BLT gaston_main_cmp2
	MOVD $0, R0
	B gaston_main_cmp3
gaston_main_cmp2:
	MOVD $1, R0
gaston_main_cmp3:
	MOVD R0, 80(RSP)
	MOVD 80(RSP), R0
	CMP $0, R0
	BEQ gaston_main_L3
	MOVD $gaston_arr(SB), R0
	MOVD 16(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 88(RSP)
	MOVD 88(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 96(RSP)
	MOVD 16(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 104(RSP)
	MOVD 104(RSP), R0
	MOVD R0, 16(RSP)
	B gaston_main_L2
gaston_main_L3:
	MOVD $gaston_arr(SB), R0
	MOVD $0, R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 112(RSP)
	MOVD $gaston_arr(SB), R0
	MOVD $1, R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 120(RSP)
	MOVD 112(RSP), R0
	MOVD 120(RSP), R1
	CALL gaston_gcd(SB)
	MOVD R0, 128(RSP)
	MOVD 128(RSP), R0
	MOVD R0, 32(RSP)
	MOVD 32(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 136(RSP)
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $144, RSP, RSP
	RET

