// Code generated by gaston — C-minus → ARM64 Plan 9 assembler
// DO NOT EDIT
//
// Runtime interface (provide these in Go):
//   func gaston_input() int64            // reads one integer from stdin
//   func gaston_output(v int64)           // writes one integer to stdout
//   func gaston_main()                    // call to run the program
#include "textflag.h"

// func main(void)
TEXT gaston_main(SB), NOSPLIT, $0
	SUB $288, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	ADD $16, RSP, R0
	MOVD R0, 48(RSP)
	MOVD 48(RSP), R0
	MOVD $0, R1
	ADD R1, R0, R0
	MOVD $1, R2
	MOVD R2, (R0)
	ADD $16, RSP, R0
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	MOVD $8, R1
	ADD R1, R0, R0
	MOVD $2, R2
	MOVD R2, (R0)
	ADD $16, RSP, R0
	MOVD R0, 64(RSP)
	MOVD 64(RSP), R0
	MOVD $16, R1
	ADD R1, R0, R0
	MOVD R0, 72(RSP)
	MOVD 72(RSP), R0
	MOVD $0, R1
	ADD R1, R0, R0
	MOVD $10, R2
	MOVD R2, (R0)
	ADD $16, RSP, R0
	MOVD R0, 80(RSP)
	MOVD 80(RSP), R0
	MOVD $16, R1
	ADD R1, R0, R0
	MOVD R0, 88(RSP)
	MOVD 88(RSP), R0
	MOVD $8, R1
	ADD R1, R0, R0
	MOVD $20, R2
	MOVD R2, (R0)
	ADD $16, RSP, R0
	MOVD R0, 96(RSP)
	MOVD 96(RSP), R0
	MOVD $0, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 104(RSP)
	MOVD 104(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 112(RSP)
	ADD $16, RSP, R0
	MOVD R0, 120(RSP)
	MOVD 120(RSP), R0
	MOVD $8, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 128(RSP)
	MOVD 128(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 136(RSP)
	ADD $16, RSP, R0
	MOVD R0, 144(RSP)
	MOVD 144(RSP), R0
	MOVD $16, R1
	ADD R1, R0, R0
	MOVD R0, 152(RSP)
	MOVD 152(RSP), R0
	MOVD $0, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 160(RSP)
	MOVD 160(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 168(RSP)
	ADD $16, RSP, R0
	MOVD R0, 176(RSP)
	MOVD 176(RSP), R0
	MOVD $16, R1
	ADD R1, R0, R0
	MOVD R0, 184(RSP)
	MOVD 184(RSP), R0
	MOVD $8, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 192(RSP)
	MOVD 192(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 200(RSP)
	ADD $16, RSP, R0
	MOVD R0, 208(RSP)
	MOVD 208(RSP), R0
	MOVD $16, R1
	ADD R1, R0, R0
	MOVD R0, 216(RSP)
	MOVD 216(RSP), R0
	MOVD $0, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 224(RSP)
	ADD $16, RSP, R0
	MOVD R0, 232(RSP)
	MOVD 232(RSP), R0
	MOVD $8, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 240(RSP)
	MOVD 224(RSP), R0
	MOVD 240(RSP), R1
	ADD R1, R0, R0
	MOVD R0, 248(RSP)
	MOVD 248(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 256(RSP)
	MOVD $16, R0
	CALL gaston_output(SB)
	MOVD R0, 264(RSP)
	MOVD $32, R0
	CALL gaston_output(SB)
	MOVD R0, 272(RSP)
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $288, RSP, RSP
	RET

