// Code generated by gaston — C-minus → ARM64 Plan 9 assembler
// DO NOT EDIT
//
// Runtime interface (provide these in Go):
//   func gaston_input() int64            // reads one integer from stdin
//   func gaston_output(v int64)           // writes one integer to stdout
//   func gaston_main()                    // call to run the program
#include "textflag.h"

// func fill(int arr[], int n)
TEXT gaston_fill(SB), NOSPLIT, $0
	SUB $64, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29
	MOVD R0, 16(RSP)
	MOVD R1, 24(RSP)

	MOVD $0, R0
	MOVD R0, 32(RSP)
gaston_fill_L0:
	MOVD 32(RSP), R0
	MOVD 24(RSP), R1
	CMP R1, R0
	BLT gaston_fill_cmp0
	MOVD $0, R0
	B gaston_fill_cmp1
gaston_fill_cmp0:
	MOVD $1, R0
gaston_fill_cmp1:
	MOVD R0, 40(RSP)
	MOVD 40(RSP), R0
	CMP $0, R0
	BEQ gaston_fill_L1
	MOVD 32(RSP), R0
	MOVD $2, R1
	MUL R1, R0, R0
	MOVD R0, 48(RSP)
	MOVD 16(RSP), R0
	MOVD 32(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD 48(RSP), R2
	MOVD R2, (R0)
	MOVD 32(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	MOVD R0, 32(RSP)
	B gaston_fill_L0
gaston_fill_L1:
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $64, RSP, RSP
	RET

// func vsum(int arr[], int n)
TEXT gaston_vsum(SB), NOSPLIT, $0
	SUB $80, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29
	MOVD R0, 16(RSP)
	MOVD R1, 24(RSP)

	MOVD $0, R0
	MOVD R0, 32(RSP)
	MOVD $0, R0
	MOVD R0, 40(RSP)
gaston_vsum_L0:
	MOVD 32(RSP), R0
	MOVD 24(RSP), R1
	CMP R1, R0
	BLT gaston_vsum_cmp0
	MOVD $0, R0
	B gaston_vsum_cmp1
gaston_vsum_cmp0:
	MOVD $1, R0
gaston_vsum_cmp1:
	MOVD R0, 48(RSP)
	MOVD 48(RSP), R0
	CMP $0, R0
	BEQ gaston_vsum_L1
	MOVD 16(RSP), R0
	MOVD 32(RSP), R1
	LSL $3, R1, R1
	ADD R1, R0, R0
	MOVD (R0), R0
	MOVD R0, 56(RSP)
	MOVD 40(RSP), R0
	MOVD 56(RSP), R1
	ADD R1, R0, R0
	MOVD R0, 64(RSP)
	MOVD 64(RSP), R0
	MOVD R0, 40(RSP)
	MOVD 32(RSP), R0
	MOVD $1, R1
	ADD R1, R0, R0
	MOVD R0, 72(RSP)
	MOVD 72(RSP), R0
	MOVD R0, 32(RSP)
	B gaston_vsum_L0
gaston_vsum_L1:
	MOVD 40(RSP), R0
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $80, RSP, RSP
	RET
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $80, RSP, RSP
	RET

// func test5(void)
TEXT gaston_test5(SB), NOSPLIT, $0
	SUB $80, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	MOVD $5, R0
	MOVD R0, 16(RSP)
	MOVD 16(RSP), R0
	LSL $3, R0, R0
	ADD $15, R0, R0
	AND $-16, R0, R0
	SUB R0, RSP, RSP
	MOVD RSP, R0
	MOVD R0, 24(RSP)
	MOVD 24(RSP), R0
	MOVD R0, 32(RSP)
	MOVD 32(RSP), R0
	MOVD 16(RSP), R1
	CALL gaston_fill(SB)
	MOVD R0, 40(RSP)
	MOVD 24(RSP), R0
	MOVD R0, 48(RSP)
	MOVD 48(RSP), R0
	MOVD 16(RSP), R1
	CALL gaston_vsum(SB)
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 64(RSP)
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $80, RSP, RSP
	RET

// func test4(void)
TEXT gaston_test4(SB), NOSPLIT, $0
	SUB $80, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	MOVD $4, R0
	MOVD R0, 16(RSP)
	MOVD 16(RSP), R0
	LSL $3, R0, R0
	ADD $15, R0, R0
	AND $-16, R0, R0
	SUB R0, RSP, RSP
	MOVD RSP, R0
	MOVD R0, 24(RSP)
	MOVD 24(RSP), R0
	MOVD R0, 32(RSP)
	MOVD 32(RSP), R0
	MOVD 16(RSP), R1
	CALL gaston_fill(SB)
	MOVD R0, 40(RSP)
	MOVD 24(RSP), R0
	MOVD R0, 48(RSP)
	MOVD 48(RSP), R0
	MOVD 16(RSP), R1
	CALL gaston_vsum(SB)
	MOVD R0, 56(RSP)
	MOVD 56(RSP), R0
	CALL gaston_output(SB)
	MOVD R0, 64(RSP)
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $80, RSP, RSP
	RET

// func main(void)
TEXT gaston_main(SB), NOSPLIT, $0
	SUB $32, RSP, RSP
	MOVD R29, 0(RSP)
	MOVD R30, 8(RSP)
	MOVD RSP, R29

	CALL gaston_test5(SB)
	MOVD R0, 16(RSP)
	CALL gaston_test4(SB)
	MOVD R0, 24(RSP)
	MOVD 0(RSP), R29
	MOVD 8(RSP), R30
	ADD $32, RSP, RSP
	RET

